// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/events/cloud/storage/v1/events.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Events.Protobuf.Cloud.Storage.V1 {

  /// <summary>Holder for reflection information generated from google/events/cloud/storage/v1/events.proto</summary>
  public static partial class EventsReflection {

    #region Descriptor
    /// <summary>File descriptor for google/events/cloud/storage/v1/events.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Citnb29nbGUvZXZlbnRzL2Nsb3VkL3N0b3JhZ2UvdjEvZXZlbnRzLnByb3Rv",
            "Eh5nb29nbGUuZXZlbnRzLmNsb3VkLnN0b3JhZ2UudjEaHmdvb2dsZS9ldmVu",
            "dHMvY2xvdWRldmVudC5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFt",
            "cC5wcm90bxoeZ29vZ2xlL3Byb3RvYnVmL3dyYXBwZXJzLnByb3RvInwKD09i",
            "amVjdEZpbmFsaXplZBI7CgRkYXRhGAEgASgLMi0uZ29vZ2xlLmV2ZW50cy5j",
            "bG91ZC5zdG9yYWdlLnYxLlN0b3JhZ2VPYmplY3Q6LILiCShnb29nbGUuY2xv",
            "dWQuc3RvcmFnZS5vYmplY3QudjEuZmluYWxpemVkInoKDk9iamVjdEFyY2hp",
            "dmVkEjsKBGRhdGEYASABKAsyLS5nb29nbGUuZXZlbnRzLmNsb3VkLnN0b3Jh",
            "Z2UudjEuU3RvcmFnZU9iamVjdDorguIJJ2dvb2dsZS5jbG91ZC5zdG9yYWdl",
            "Lm9iamVjdC52MS5hcmNoaXZlZCJ4Cg1PYmplY3REZWxldGVkEjsKBGRhdGEY",
            "ASABKAsyLS5nb29nbGUuZXZlbnRzLmNsb3VkLnN0b3JhZ2UudjEuU3RvcmFn",
            "ZU9iamVjdDoqguIJJmdvb2dsZS5jbG91ZC5zdG9yYWdlLm9iamVjdC52MS5k",
            "ZWxldGVkIogBChVPYmplY3RNZXRhZGF0YVVwZGF0ZWQSOwoEZGF0YRgBIAEo",
            "CzItLmdvb2dsZS5ldmVudHMuY2xvdWQuc3RvcmFnZS52MS5TdG9yYWdlT2Jq",
            "ZWN0OjKC4gkuZ29vZ2xlLmNsb3VkLnN0b3JhZ2Uub2JqZWN0LnYxLm1ldGFk",
            "YXRhVXBkYXRlZCIPCg1TdG9yYWdlQnVja2V0IuwHCg1TdG9yYWdlT2JqZWN0",
            "EhgKEGNvbnRlbnRfZW5jb2RpbmcYASABKAkSGwoTY29udGVudF9kaXNwb3Np",
            "dGlvbhgCIAEoCRIVCg1jYWNoZV9jb250cm9sGAMgASgJEhgKEGNvbnRlbnRf",
            "bGFuZ3VhZ2UYBSABKAkSFgoObWV0YWdlbmVyYXRpb24YBiABKAMSMAoMdGlt",
            "ZV9kZWxldGVkGAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIU",
            "Cgxjb250ZW50X3R5cGUYCCABKAkSDAoEc2l6ZRgJIAEoAxIwCgx0aW1lX2Ny",
            "ZWF0ZWQYCiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEg4KBmNy",
            "YzMyYxgLIAEoDBIXCg9jb21wb25lbnRfY291bnQYDCABKAUSEAoIbWQ1X2hh",
            "c2gYDSABKAkSDAoEZXRhZxgOIAEoCRIrCgd1cGRhdGVkGA8gASgLMhouZ29v",
            "Z2xlLnByb3RvYnVmLlRpbWVzdGFtcBIVCg1zdG9yYWdlX2NsYXNzGBAgASgJ",
            "EhQKDGttc19rZXlfbmFtZRgRIAEoCRI+Chp0aW1lX3N0b3JhZ2VfY2xhc3Nf",
            "dXBkYXRlZBgSIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASFgoO",
            "dGVtcG9yYXJ5X2hvbGQYEyABKAgSPQoZcmV0ZW50aW9uX2V4cGlyYXRpb25f",
            "dGltZRgUIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASTQoIbWV0",
            "YWRhdGEYFSADKAsyOy5nb29nbGUuZXZlbnRzLmNsb3VkLnN0b3JhZ2UudjEu",
            "U3RvcmFnZU9iamVjdC5NZXRhZGF0YUVudHJ5EjQKEGV2ZW50X2Jhc2VkX2hv",
            "bGQYHSABKAsyGi5nb29nbGUucHJvdG9idWYuQm9vbFZhbHVlEgwKBG5hbWUY",
            "FyABKAkSCgoCaWQYGCABKAkSDgoGYnVja2V0GBkgASgJEhIKCmdlbmVyYXRp",
            "b24YGiABKAMSXQoTY3VzdG9tZXJfZW5jcnlwdGlvbhgcIAEoCzJALmdvb2ds",
            "ZS5ldmVudHMuY2xvdWQuc3RvcmFnZS52MS5TdG9yYWdlT2JqZWN0LkN1c3Rv",
            "bWVyRW5jcnlwdGlvbhpGChJDdXN0b21lckVuY3J5cHRpb24SHAoUZW5jcnlw",
            "dGlvbl9hbGdvcml0aG0YASABKAkSEgoKa2V5X3NoYTI1NhgCIAEoCRovCg1N",
            "ZXRhZGF0YUVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAFC",
            "KqoCJ0dvb2dsZS5FdmVudHMuUHJvdG9idWYuQ2xvdWQuU3RvcmFnZS5WMWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Events.Protobuf.CloudeventReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Storage.V1.ObjectFinalized), global::Google.Events.Protobuf.Cloud.Storage.V1.ObjectFinalized.Parser, new[]{ "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Storage.V1.ObjectArchived), global::Google.Events.Protobuf.Cloud.Storage.V1.ObjectArchived.Parser, new[]{ "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Storage.V1.ObjectDeleted), global::Google.Events.Protobuf.Cloud.Storage.V1.ObjectDeleted.Parser, new[]{ "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Storage.V1.ObjectMetadataUpdated), global::Google.Events.Protobuf.Cloud.Storage.V1.ObjectMetadataUpdated.Parser, new[]{ "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Storage.V1.StorageBucket), global::Google.Events.Protobuf.Cloud.Storage.V1.StorageBucket.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject), global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject.Parser, new[]{ "ContentEncoding", "ContentDisposition", "CacheControl", "ContentLanguage", "Metageneration", "TimeDeleted", "ContentType", "Size", "TimeCreated", "Crc32C", "ComponentCount", "Md5Hash", "Etag", "Updated", "StorageClass", "KmsKeyName", "TimeStorageClassUpdated", "TemporaryHold", "RetentionExpirationTime", "Metadata", "EventBasedHold", "Name", "Id", "Bucket", "Generation", "CustomerEncryption" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject.Types.CustomerEncryption), global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject.Types.CustomerEncryption.Parser, new[]{ "EncryptionAlgorithm", "KeySha256" }, null, null, null, null),
            null, })
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// The CloudEvent raised when an object is finalized in Google Cloud Storage.
  /// </summary>
  public sealed partial class ObjectFinalized : pb::IMessage<ObjectFinalized> {
    private static readonly pb::MessageParser<ObjectFinalized> _parser = new pb::MessageParser<ObjectFinalized>(() => new ObjectFinalized());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ObjectFinalized> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Storage.V1.EventsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectFinalized() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectFinalized(ObjectFinalized other) : this() {
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectFinalized Clone() {
      return new ObjectFinalized(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject data_;
    /// <summary>
    /// The data associated with the event.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ObjectFinalized);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ObjectFinalized other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ObjectFinalized other) {
      if (other == null) {
        return;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (data_ == null) {
              Data = new global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// The CloudEvent raised when an object is archived in Google Cloud Storage.
  /// </summary>
  public sealed partial class ObjectArchived : pb::IMessage<ObjectArchived> {
    private static readonly pb::MessageParser<ObjectArchived> _parser = new pb::MessageParser<ObjectArchived>(() => new ObjectArchived());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ObjectArchived> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Storage.V1.EventsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectArchived() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectArchived(ObjectArchived other) : this() {
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectArchived Clone() {
      return new ObjectArchived(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject data_;
    /// <summary>
    /// The data associated with the event.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ObjectArchived);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ObjectArchived other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ObjectArchived other) {
      if (other == null) {
        return;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (data_ == null) {
              Data = new global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// The CloudEvent raised when an object is deleted  in Google Cloud Storage.
  /// </summary>
  public sealed partial class ObjectDeleted : pb::IMessage<ObjectDeleted> {
    private static readonly pb::MessageParser<ObjectDeleted> _parser = new pb::MessageParser<ObjectDeleted>(() => new ObjectDeleted());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ObjectDeleted> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Storage.V1.EventsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectDeleted() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectDeleted(ObjectDeleted other) : this() {
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectDeleted Clone() {
      return new ObjectDeleted(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject data_;
    /// <summary>
    /// The data associated with the event.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ObjectDeleted);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ObjectDeleted other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ObjectDeleted other) {
      if (other == null) {
        return;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (data_ == null) {
              Data = new global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// The CloudEvent raised when an object's metadata is updated  in Google Cloud Storage.
  /// </summary>
  public sealed partial class ObjectMetadataUpdated : pb::IMessage<ObjectMetadataUpdated> {
    private static readonly pb::MessageParser<ObjectMetadataUpdated> _parser = new pb::MessageParser<ObjectMetadataUpdated>(() => new ObjectMetadataUpdated());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ObjectMetadataUpdated> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Storage.V1.EventsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectMetadataUpdated() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectMetadataUpdated(ObjectMetadataUpdated other) : this() {
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ObjectMetadataUpdated Clone() {
      return new ObjectMetadataUpdated(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject data_;
    /// <summary>
    /// The data associated with the event.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ObjectMetadataUpdated);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ObjectMetadataUpdated other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ObjectMetadataUpdated other) {
      if (other == null) {
        return;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (data_ == null) {
              Data = new global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// A bucket within Google Cloud Storage.
  /// Note: even if we don't have any events which emit a bucket at the moment,
  /// I'm sure we will at some point.
  /// </summary>
  public sealed partial class StorageBucket : pb::IMessage<StorageBucket> {
    private static readonly pb::MessageParser<StorageBucket> _parser = new pb::MessageParser<StorageBucket>(() => new StorageBucket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StorageBucket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Storage.V1.EventsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageBucket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageBucket(StorageBucket other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageBucket Clone() {
      return new StorageBucket(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StorageBucket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StorageBucket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StorageBucket other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  /// <summary>
  /// An object within Google Cloud Storage.
  /// </summary>
  public sealed partial class StorageObject : pb::IMessage<StorageObject> {
    private static readonly pb::MessageParser<StorageObject> _parser = new pb::MessageParser<StorageObject>(() => new StorageObject());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StorageObject> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Storage.V1.EventsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageObject() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageObject(StorageObject other) : this() {
      contentEncoding_ = other.contentEncoding_;
      contentDisposition_ = other.contentDisposition_;
      cacheControl_ = other.cacheControl_;
      contentLanguage_ = other.contentLanguage_;
      metageneration_ = other.metageneration_;
      timeDeleted_ = other.timeDeleted_ != null ? other.timeDeleted_.Clone() : null;
      contentType_ = other.contentType_;
      size_ = other.size_;
      timeCreated_ = other.timeCreated_ != null ? other.timeCreated_.Clone() : null;
      crc32C_ = other.crc32C_;
      componentCount_ = other.componentCount_;
      md5Hash_ = other.md5Hash_;
      etag_ = other.etag_;
      updated_ = other.updated_ != null ? other.updated_.Clone() : null;
      storageClass_ = other.storageClass_;
      kmsKeyName_ = other.kmsKeyName_;
      timeStorageClassUpdated_ = other.timeStorageClassUpdated_ != null ? other.timeStorageClassUpdated_.Clone() : null;
      temporaryHold_ = other.temporaryHold_;
      retentionExpirationTime_ = other.retentionExpirationTime_ != null ? other.retentionExpirationTime_.Clone() : null;
      metadata_ = other.metadata_.Clone();
      EventBasedHold = other.EventBasedHold;
      name_ = other.name_;
      id_ = other.id_;
      bucket_ = other.bucket_;
      generation_ = other.generation_;
      customerEncryption_ = other.customerEncryption_ != null ? other.customerEncryption_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageObject Clone() {
      return new StorageObject(this);
    }

    /// <summary>Field number for the "content_encoding" field.</summary>
    public const int ContentEncodingFieldNumber = 1;
    private string contentEncoding_ = "";
    /// <summary>
    /// Content-Encoding of the object data, matching
    /// [https://tools.ietf.org/html/rfc7231#section-3.1.2.2][RFC 7231 §3.1.2.2]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ContentEncoding {
      get { return contentEncoding_; }
      set {
        contentEncoding_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content_disposition" field.</summary>
    public const int ContentDispositionFieldNumber = 2;
    private string contentDisposition_ = "";
    /// <summary>
    /// Content-Disposition of the object data, matching
    /// [https://tools.ietf.org/html/rfc6266][RFC 6266].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ContentDisposition {
      get { return contentDisposition_; }
      set {
        contentDisposition_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cache_control" field.</summary>
    public const int CacheControlFieldNumber = 3;
    private string cacheControl_ = "";
    /// <summary>
    /// Cache-Control directive for the object data, matching
    /// [https://tools.ietf.org/html/rfc7234#section-5.2"][RFC 7234 §5.2].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CacheControl {
      get { return cacheControl_; }
      set {
        cacheControl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content_language" field.</summary>
    public const int ContentLanguageFieldNumber = 5;
    private string contentLanguage_ = "";
    /// <summary>
    /// Content-Language of the object data, matching
    /// [https://tools.ietf.org/html/rfc7231#section-3.1.3.2][RFC 7231 §3.1.3.2].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ContentLanguage {
      get { return contentLanguage_; }
      set {
        contentLanguage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "metageneration" field.</summary>
    public const int MetagenerationFieldNumber = 6;
    private long metageneration_;
    /// <summary>
    /// The version of the metadata for this object at this generation. Used for
    /// preconditions and for detecting changes in metadata. A metageneration
    /// number is only meaningful in the context of a particular generation of a
    /// particular object.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Metageneration {
      get { return metageneration_; }
      set {
        metageneration_ = value;
      }
    }

    /// <summary>Field number for the "time_deleted" field.</summary>
    public const int TimeDeletedFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timeDeleted_;
    /// <summary>
    /// The deletion time of the object. Will be returned if and only if this
    /// version of the object has been deleted.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimeDeleted {
      get { return timeDeleted_; }
      set {
        timeDeleted_ = value;
      }
    }

    /// <summary>Field number for the "content_type" field.</summary>
    public const int ContentTypeFieldNumber = 8;
    private string contentType_ = "";
    /// <summary>
    /// Content-Type of the object data, matching
    /// [https://tools.ietf.org/html/rfc7231#section-3.1.1.5][RFC 7231 §3.1.1.5].
    /// If an object is stored without a Content-Type, it is served as
    /// `application/octet-stream`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ContentType {
      get { return contentType_; }
      set {
        contentType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 9;
    private long size_;
    /// <summary>
    /// Content-Length of the object data in bytes, matching
    /// [https://tools.ietf.org/html/rfc7230#section-3.3.2][RFC 7230 §3.3.2].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "time_created" field.</summary>
    public const int TimeCreatedFieldNumber = 10;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timeCreated_;
    /// <summary>
    /// The creation time of the object.
    /// Attempting to set this field will result in an error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimeCreated {
      get { return timeCreated_; }
      set {
        timeCreated_ = value;
      }
    }

    /// <summary>Field number for the "crc32c" field.</summary>
    public const int Crc32CFieldNumber = 11;
    private pb::ByteString crc32C_ = pb::ByteString.Empty;
    /// <summary>
    /// CRC32c checksum. For more information about using the CRC32c
    /// checksum, see
    /// [https://cloud.google.com/storage/docs/hashes-etags#_JSONAPI][Hashes and
    /// ETags: Best Practices].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Crc32C {
      get { return crc32C_; }
      set {
        crc32C_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "component_count" field.</summary>
    public const int ComponentCountFieldNumber = 12;
    private int componentCount_;
    /// <summary>
    /// Number of underlying components that make up this object. Components are
    /// accumulated by compose operations.
    /// Attempting to set this field will result in an error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ComponentCount {
      get { return componentCount_; }
      set {
        componentCount_ = value;
      }
    }

    /// <summary>Field number for the "md5_hash" field.</summary>
    public const int Md5HashFieldNumber = 13;
    private string md5Hash_ = "";
    /// <summary>
    /// MD5 hash of the data; encoded using base64 as per
    /// [https://tools.ietf.org/html/rfc4648#section-4][RFC 4648 §4]. For more
    /// information about using the MD5 hash, see
    /// [https://cloud.google.com/storage/docs/hashes-etags#_JSONAPI][Hashes and
    /// ETags: Best Practices].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Md5Hash {
      get { return md5Hash_; }
      set {
        md5Hash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "etag" field.</summary>
    public const int EtagFieldNumber = 14;
    private string etag_ = "";
    /// <summary>
    /// HTTP 1.1 Entity tag for the object. See
    /// [https://tools.ietf.org/html/rfc7232#section-2.3][RFC 7232 §2.3].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Etag {
      get { return etag_; }
      set {
        etag_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "updated" field.</summary>
    public const int UpdatedFieldNumber = 15;
    private global::Google.Protobuf.WellKnownTypes.Timestamp updated_;
    /// <summary>
    /// The modification time of the object metadata.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Updated {
      get { return updated_; }
      set {
        updated_ = value;
      }
    }

    /// <summary>Field number for the "storage_class" field.</summary>
    public const int StorageClassFieldNumber = 16;
    private string storageClass_ = "";
    /// <summary>
    /// Storage class of the object.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StorageClass {
      get { return storageClass_; }
      set {
        storageClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "kms_key_name" field.</summary>
    public const int KmsKeyNameFieldNumber = 17;
    private string kmsKeyName_ = "";
    /// <summary>
    /// Cloud KMS Key used to encrypt this object, if the object is encrypted by
    /// such a key.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string KmsKeyName {
      get { return kmsKeyName_; }
      set {
        kmsKeyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "time_storage_class_updated" field.</summary>
    public const int TimeStorageClassUpdatedFieldNumber = 18;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timeStorageClassUpdated_;
    /// <summary>
    /// The time at which the object's storage class was last changed.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimeStorageClassUpdated {
      get { return timeStorageClassUpdated_; }
      set {
        timeStorageClassUpdated_ = value;
      }
    }

    /// <summary>Field number for the "temporary_hold" field.</summary>
    public const int TemporaryHoldFieldNumber = 19;
    private bool temporaryHold_;
    /// <summary>
    /// Whether an object is under temporary hold.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool TemporaryHold {
      get { return temporaryHold_; }
      set {
        temporaryHold_ = value;
      }
    }

    /// <summary>Field number for the "retention_expiration_time" field.</summary>
    public const int RetentionExpirationTimeFieldNumber = 20;
    private global::Google.Protobuf.WellKnownTypes.Timestamp retentionExpirationTime_;
    /// <summary>
    /// A server-determined value that specifies the earliest time that the
    /// object's retention period expires.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp RetentionExpirationTime {
      get { return retentionExpirationTime_; }
      set {
        retentionExpirationTime_ = value;
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 21;
    private static readonly pbc::MapField<string, string>.Codec _map_metadata_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 170);
    private readonly pbc::MapField<string, string> metadata_ = new pbc::MapField<string, string>();
    /// <summary>
    /// User-provided metadata, in key/value pairs.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Metadata {
      get { return metadata_; }
    }

    /// <summary>Field number for the "event_based_hold" field.</summary>
    public const int EventBasedHoldFieldNumber = 29;
    private static readonly pb::FieldCodec<bool?> _single_eventBasedHold_codec = pb::FieldCodec.ForStructWrapper<bool>(234);
    private bool? eventBasedHold_;
    /// <summary>
    /// Whether an object is under event-based hold.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool? EventBasedHold {
      get { return eventBasedHold_; }
      set {
        eventBasedHold_ = value;
      }
    }


    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 23;
    private string name_ = "";
    /// <summary>
    /// The name of the object.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 24;
    private string id_ = "";
    /// <summary>
    /// The ID of the object, including the bucket name, object name, and
    /// generation number.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bucket" field.</summary>
    public const int BucketFieldNumber = 25;
    private string bucket_ = "";
    /// <summary>
    /// The name of the bucket containing this object.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Bucket {
      get { return bucket_; }
      set {
        bucket_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "generation" field.</summary>
    public const int GenerationFieldNumber = 26;
    private long generation_;
    /// <summary>
    /// The content generation of this object. Used for object versioning.
    /// Attempting to set this field will result in an error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Generation {
      get { return generation_; }
      set {
        generation_ = value;
      }
    }

    /// <summary>Field number for the "customer_encryption" field.</summary>
    public const int CustomerEncryptionFieldNumber = 28;
    private global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject.Types.CustomerEncryption customerEncryption_;
    /// <summary>
    /// Metadata of customer-supplied encryption key, if the object is encrypted by
    /// such a key.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject.Types.CustomerEncryption CustomerEncryption {
      get { return customerEncryption_; }
      set {
        customerEncryption_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StorageObject);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StorageObject other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ContentEncoding != other.ContentEncoding) return false;
      if (ContentDisposition != other.ContentDisposition) return false;
      if (CacheControl != other.CacheControl) return false;
      if (ContentLanguage != other.ContentLanguage) return false;
      if (Metageneration != other.Metageneration) return false;
      if (!object.Equals(TimeDeleted, other.TimeDeleted)) return false;
      if (ContentType != other.ContentType) return false;
      if (Size != other.Size) return false;
      if (!object.Equals(TimeCreated, other.TimeCreated)) return false;
      if (Crc32C != other.Crc32C) return false;
      if (ComponentCount != other.ComponentCount) return false;
      if (Md5Hash != other.Md5Hash) return false;
      if (Etag != other.Etag) return false;
      if (!object.Equals(Updated, other.Updated)) return false;
      if (StorageClass != other.StorageClass) return false;
      if (KmsKeyName != other.KmsKeyName) return false;
      if (!object.Equals(TimeStorageClassUpdated, other.TimeStorageClassUpdated)) return false;
      if (TemporaryHold != other.TemporaryHold) return false;
      if (!object.Equals(RetentionExpirationTime, other.RetentionExpirationTime)) return false;
      if (!Metadata.Equals(other.Metadata)) return false;
      if (EventBasedHold != other.EventBasedHold) return false;
      if (Name != other.Name) return false;
      if (Id != other.Id) return false;
      if (Bucket != other.Bucket) return false;
      if (Generation != other.Generation) return false;
      if (!object.Equals(CustomerEncryption, other.CustomerEncryption)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ContentEncoding.Length != 0) hash ^= ContentEncoding.GetHashCode();
      if (ContentDisposition.Length != 0) hash ^= ContentDisposition.GetHashCode();
      if (CacheControl.Length != 0) hash ^= CacheControl.GetHashCode();
      if (ContentLanguage.Length != 0) hash ^= ContentLanguage.GetHashCode();
      if (Metageneration != 0L) hash ^= Metageneration.GetHashCode();
      if (timeDeleted_ != null) hash ^= TimeDeleted.GetHashCode();
      if (ContentType.Length != 0) hash ^= ContentType.GetHashCode();
      if (Size != 0L) hash ^= Size.GetHashCode();
      if (timeCreated_ != null) hash ^= TimeCreated.GetHashCode();
      if (Crc32C.Length != 0) hash ^= Crc32C.GetHashCode();
      if (ComponentCount != 0) hash ^= ComponentCount.GetHashCode();
      if (Md5Hash.Length != 0) hash ^= Md5Hash.GetHashCode();
      if (Etag.Length != 0) hash ^= Etag.GetHashCode();
      if (updated_ != null) hash ^= Updated.GetHashCode();
      if (StorageClass.Length != 0) hash ^= StorageClass.GetHashCode();
      if (KmsKeyName.Length != 0) hash ^= KmsKeyName.GetHashCode();
      if (timeStorageClassUpdated_ != null) hash ^= TimeStorageClassUpdated.GetHashCode();
      if (TemporaryHold != false) hash ^= TemporaryHold.GetHashCode();
      if (retentionExpirationTime_ != null) hash ^= RetentionExpirationTime.GetHashCode();
      hash ^= Metadata.GetHashCode();
      if (eventBasedHold_ != null) hash ^= EventBasedHold.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Bucket.Length != 0) hash ^= Bucket.GetHashCode();
      if (Generation != 0L) hash ^= Generation.GetHashCode();
      if (customerEncryption_ != null) hash ^= CustomerEncryption.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ContentEncoding.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ContentEncoding);
      }
      if (ContentDisposition.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ContentDisposition);
      }
      if (CacheControl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CacheControl);
      }
      if (ContentLanguage.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ContentLanguage);
      }
      if (Metageneration != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Metageneration);
      }
      if (timeDeleted_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(TimeDeleted);
      }
      if (ContentType.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ContentType);
      }
      if (Size != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(Size);
      }
      if (timeCreated_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(TimeCreated);
      }
      if (Crc32C.Length != 0) {
        output.WriteRawTag(90);
        output.WriteBytes(Crc32C);
      }
      if (ComponentCount != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(ComponentCount);
      }
      if (Md5Hash.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Md5Hash);
      }
      if (Etag.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(Etag);
      }
      if (updated_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(Updated);
      }
      if (StorageClass.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(StorageClass);
      }
      if (KmsKeyName.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(KmsKeyName);
      }
      if (timeStorageClassUpdated_ != null) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(TimeStorageClassUpdated);
      }
      if (TemporaryHold != false) {
        output.WriteRawTag(152, 1);
        output.WriteBool(TemporaryHold);
      }
      if (retentionExpirationTime_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(RetentionExpirationTime);
      }
      metadata_.WriteTo(output, _map_metadata_codec);
      if (Name.Length != 0) {
        output.WriteRawTag(186, 1);
        output.WriteString(Name);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(194, 1);
        output.WriteString(Id);
      }
      if (Bucket.Length != 0) {
        output.WriteRawTag(202, 1);
        output.WriteString(Bucket);
      }
      if (Generation != 0L) {
        output.WriteRawTag(208, 1);
        output.WriteInt64(Generation);
      }
      if (customerEncryption_ != null) {
        output.WriteRawTag(226, 1);
        output.WriteMessage(CustomerEncryption);
      }
      if (eventBasedHold_ != null) {
        _single_eventBasedHold_codec.WriteTagAndValue(output, EventBasedHold);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ContentEncoding.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContentEncoding);
      }
      if (ContentDisposition.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContentDisposition);
      }
      if (CacheControl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CacheControl);
      }
      if (ContentLanguage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContentLanguage);
      }
      if (Metageneration != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Metageneration);
      }
      if (timeDeleted_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeDeleted);
      }
      if (ContentType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContentType);
      }
      if (Size != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Size);
      }
      if (timeCreated_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeCreated);
      }
      if (Crc32C.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Crc32C);
      }
      if (ComponentCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ComponentCount);
      }
      if (Md5Hash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Md5Hash);
      }
      if (Etag.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Etag);
      }
      if (updated_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Updated);
      }
      if (StorageClass.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(StorageClass);
      }
      if (KmsKeyName.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(KmsKeyName);
      }
      if (timeStorageClassUpdated_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(TimeStorageClassUpdated);
      }
      if (TemporaryHold != false) {
        size += 2 + 1;
      }
      if (retentionExpirationTime_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(RetentionExpirationTime);
      }
      size += metadata_.CalculateSize(_map_metadata_codec);
      if (eventBasedHold_ != null) {
        size += _single_eventBasedHold_codec.CalculateSizeWithTag(EventBasedHold);
      }
      if (Name.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Id.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Bucket.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Bucket);
      }
      if (Generation != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Generation);
      }
      if (customerEncryption_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(CustomerEncryption);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StorageObject other) {
      if (other == null) {
        return;
      }
      if (other.ContentEncoding.Length != 0) {
        ContentEncoding = other.ContentEncoding;
      }
      if (other.ContentDisposition.Length != 0) {
        ContentDisposition = other.ContentDisposition;
      }
      if (other.CacheControl.Length != 0) {
        CacheControl = other.CacheControl;
      }
      if (other.ContentLanguage.Length != 0) {
        ContentLanguage = other.ContentLanguage;
      }
      if (other.Metageneration != 0L) {
        Metageneration = other.Metageneration;
      }
      if (other.timeDeleted_ != null) {
        if (timeDeleted_ == null) {
          TimeDeleted = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimeDeleted.MergeFrom(other.TimeDeleted);
      }
      if (other.ContentType.Length != 0) {
        ContentType = other.ContentType;
      }
      if (other.Size != 0L) {
        Size = other.Size;
      }
      if (other.timeCreated_ != null) {
        if (timeCreated_ == null) {
          TimeCreated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimeCreated.MergeFrom(other.TimeCreated);
      }
      if (other.Crc32C.Length != 0) {
        Crc32C = other.Crc32C;
      }
      if (other.ComponentCount != 0) {
        ComponentCount = other.ComponentCount;
      }
      if (other.Md5Hash.Length != 0) {
        Md5Hash = other.Md5Hash;
      }
      if (other.Etag.Length != 0) {
        Etag = other.Etag;
      }
      if (other.updated_ != null) {
        if (updated_ == null) {
          Updated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Updated.MergeFrom(other.Updated);
      }
      if (other.StorageClass.Length != 0) {
        StorageClass = other.StorageClass;
      }
      if (other.KmsKeyName.Length != 0) {
        KmsKeyName = other.KmsKeyName;
      }
      if (other.timeStorageClassUpdated_ != null) {
        if (timeStorageClassUpdated_ == null) {
          TimeStorageClassUpdated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimeStorageClassUpdated.MergeFrom(other.TimeStorageClassUpdated);
      }
      if (other.TemporaryHold != false) {
        TemporaryHold = other.TemporaryHold;
      }
      if (other.retentionExpirationTime_ != null) {
        if (retentionExpirationTime_ == null) {
          RetentionExpirationTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        RetentionExpirationTime.MergeFrom(other.RetentionExpirationTime);
      }
      metadata_.Add(other.metadata_);
      if (other.eventBasedHold_ != null) {
        if (eventBasedHold_ == null || other.EventBasedHold != false) {
          EventBasedHold = other.EventBasedHold;
        }
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Bucket.Length != 0) {
        Bucket = other.Bucket;
      }
      if (other.Generation != 0L) {
        Generation = other.Generation;
      }
      if (other.customerEncryption_ != null) {
        if (customerEncryption_ == null) {
          CustomerEncryption = new global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject.Types.CustomerEncryption();
        }
        CustomerEncryption.MergeFrom(other.CustomerEncryption);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ContentEncoding = input.ReadString();
            break;
          }
          case 18: {
            ContentDisposition = input.ReadString();
            break;
          }
          case 26: {
            CacheControl = input.ReadString();
            break;
          }
          case 42: {
            ContentLanguage = input.ReadString();
            break;
          }
          case 48: {
            Metageneration = input.ReadInt64();
            break;
          }
          case 58: {
            if (timeDeleted_ == null) {
              TimeDeleted = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimeDeleted);
            break;
          }
          case 66: {
            ContentType = input.ReadString();
            break;
          }
          case 72: {
            Size = input.ReadInt64();
            break;
          }
          case 82: {
            if (timeCreated_ == null) {
              TimeCreated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimeCreated);
            break;
          }
          case 90: {
            Crc32C = input.ReadBytes();
            break;
          }
          case 96: {
            ComponentCount = input.ReadInt32();
            break;
          }
          case 106: {
            Md5Hash = input.ReadString();
            break;
          }
          case 114: {
            Etag = input.ReadString();
            break;
          }
          case 122: {
            if (updated_ == null) {
              Updated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Updated);
            break;
          }
          case 130: {
            StorageClass = input.ReadString();
            break;
          }
          case 138: {
            KmsKeyName = input.ReadString();
            break;
          }
          case 146: {
            if (timeStorageClassUpdated_ == null) {
              TimeStorageClassUpdated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimeStorageClassUpdated);
            break;
          }
          case 152: {
            TemporaryHold = input.ReadBool();
            break;
          }
          case 162: {
            if (retentionExpirationTime_ == null) {
              RetentionExpirationTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(RetentionExpirationTime);
            break;
          }
          case 170: {
            metadata_.AddEntriesFrom(input, _map_metadata_codec);
            break;
          }
          case 186: {
            Name = input.ReadString();
            break;
          }
          case 194: {
            Id = input.ReadString();
            break;
          }
          case 202: {
            Bucket = input.ReadString();
            break;
          }
          case 208: {
            Generation = input.ReadInt64();
            break;
          }
          case 226: {
            if (customerEncryption_ == null) {
              CustomerEncryption = new global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject.Types.CustomerEncryption();
            }
            input.ReadMessage(CustomerEncryption);
            break;
          }
          case 234: {
            bool? value = _single_eventBasedHold_codec.Read(input);
            if (eventBasedHold_ == null || value != false) {
              EventBasedHold = value;
            }
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the StorageObject message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// Describes the customer-specified mechanism used to store the data at rest.
      /// </summary>
      public sealed partial class CustomerEncryption : pb::IMessage<CustomerEncryption> {
        private static readonly pb::MessageParser<CustomerEncryption> _parser = new pb::MessageParser<CustomerEncryption>(() => new CustomerEncryption());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<CustomerEncryption> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObject.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CustomerEncryption() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CustomerEncryption(CustomerEncryption other) : this() {
          encryptionAlgorithm_ = other.encryptionAlgorithm_;
          keySha256_ = other.keySha256_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CustomerEncryption Clone() {
          return new CustomerEncryption(this);
        }

        /// <summary>Field number for the "encryption_algorithm" field.</summary>
        public const int EncryptionAlgorithmFieldNumber = 1;
        private string encryptionAlgorithm_ = "";
        /// <summary>
        /// The encryption algorithm.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string EncryptionAlgorithm {
          get { return encryptionAlgorithm_; }
          set {
            encryptionAlgorithm_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "key_sha256" field.</summary>
        public const int KeySha256FieldNumber = 2;
        private string keySha256_ = "";
        /// <summary>
        /// SHA256 hash value of the encryption key.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string KeySha256 {
          get { return keySha256_; }
          set {
            keySha256_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as CustomerEncryption);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(CustomerEncryption other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (EncryptionAlgorithm != other.EncryptionAlgorithm) return false;
          if (KeySha256 != other.KeySha256) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (EncryptionAlgorithm.Length != 0) hash ^= EncryptionAlgorithm.GetHashCode();
          if (KeySha256.Length != 0) hash ^= KeySha256.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (EncryptionAlgorithm.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(EncryptionAlgorithm);
          }
          if (KeySha256.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(KeySha256);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (EncryptionAlgorithm.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(EncryptionAlgorithm);
          }
          if (KeySha256.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(KeySha256);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(CustomerEncryption other) {
          if (other == null) {
            return;
          }
          if (other.EncryptionAlgorithm.Length != 0) {
            EncryptionAlgorithm = other.EncryptionAlgorithm;
          }
          if (other.KeySha256.Length != 0) {
            KeySha256 = other.KeySha256;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                EncryptionAlgorithm = input.ReadString();
                break;
              }
              case 18: {
                KeySha256 = input.ReadString();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
