// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/events/cloud/audit/v1/events.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Events.Protobuf.Cloud.Audit.V1 {

  /// <summary>Holder for reflection information generated from google/events/cloud/audit/v1/events.proto</summary>
  public static partial class EventsReflection {

    #region Descriptor
    /// <summary>File descriptor for google/events/cloud/audit/v1/events.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cilnb29nbGUvZXZlbnRzL2Nsb3VkL2F1ZGl0L3YxL2V2ZW50cy5wcm90bxIc",
            "Z29vZ2xlLmV2ZW50cy5jbG91ZC5hdWRpdC52MRoeZ29vZ2xlL2V2ZW50cy9j",
            "bG91ZGV2ZW50LnByb3RvGhxnb29nbGUvcHJvdG9idWYvc3RydWN0LnByb3Rv",
            "Ghdnb29nbGUvcnBjL3N0YXR1cy5wcm90byJyCg9BdWRpdExvZ0NyZWF0ZWQS",
            "OAoEZGF0YRgBIAEoCzIqLmdvb2dsZS5ldmVudHMuY2xvdWQuYXVkaXQudjEu",
            "QXVkaXRMb2dEYXRhOiWC4gkhZ29vZ2xlLmNsb3VkLmF1ZGl0LmxvZy52MS5j",
            "cmVhdGVkIvkDCgxBdWRpdExvZ0RhdGESFAoMc2VydmljZV9uYW1lGAcgASgJ",
            "EhMKC21ldGhvZF9uYW1lGAggASgJEhUKDXJlc291cmNlX25hbWUYCyABKAkS",
            "GgoSbnVtX3Jlc3BvbnNlX2l0ZW1zGAwgASgDEiIKBnN0YXR1cxgCIAEoCzIS",
            "Lmdvb2dsZS5ycGMuU3RhdHVzEk0KE2F1dGhlbnRpY2F0aW9uX2luZm8YAyAB",
            "KAsyMC5nb29nbGUuZXZlbnRzLmNsb3VkLmF1ZGl0LnYxLkF1dGhlbnRpY2F0",
            "aW9uSW5mbxJLChJhdXRob3JpemF0aW9uX2luZm8YCSADKAsyLy5nb29nbGUu",
            "ZXZlbnRzLmNsb3VkLmF1ZGl0LnYxLkF1dGhvcml6YXRpb25JbmZvEkcKEHJl",
            "cXVlc3RfbWV0YWRhdGEYBCABKAsyLS5nb29nbGUuZXZlbnRzLmNsb3VkLmF1",
            "ZGl0LnYxLlJlcXVlc3RNZXRhZGF0YRIoCgdyZXF1ZXN0GBAgASgLMhcuZ29v",
            "Z2xlLnByb3RvYnVmLlN0cnVjdBIpCghyZXNwb25zZRgRIAEoCzIXLmdvb2ds",
            "ZS5wcm90b2J1Zi5TdHJ1Y3QSLQoMc2VydmljZV9kYXRhGA8gASgLMhcuZ29v",
            "Z2xlLnByb3RvYnVmLlN0cnVjdCItChJBdXRoZW50aWNhdGlvbkluZm8SFwoP",
            "cHJpbmNpcGFsX2VtYWlsGAEgASgJIkoKEUF1dGhvcml6YXRpb25JbmZvEhAK",
            "CHJlc291cmNlGAEgASgJEhIKCnBlcm1pc3Npb24YAiABKAkSDwoHZ3JhbnRl",
            "ZBgDIAEoCCJICg9SZXF1ZXN0TWV0YWRhdGESEQoJY2FsbGVyX2lwGAEgASgJ",
            "EiIKGmNhbGxlcl9zdXBwbGllZF91c2VyX2FnZW50GAIgASgJQiiqAiVHb29n",
            "bGUuRXZlbnRzLlByb3RvYnVmLkNsb3VkLkF1ZGl0LlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Events.Protobuf.CloudeventReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, global::Google.Rpc.StatusReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Audit.V1.AuditLogCreated), global::Google.Events.Protobuf.Cloud.Audit.V1.AuditLogCreated.Parser, new[]{ "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Audit.V1.AuditLogData), global::Google.Events.Protobuf.Cloud.Audit.V1.AuditLogData.Parser, new[]{ "ServiceName", "MethodName", "ResourceName", "NumResponseItems", "Status", "AuthenticationInfo", "AuthorizationInfo", "RequestMetadata", "Request", "Response", "ServiceData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Audit.V1.AuthenticationInfo), global::Google.Events.Protobuf.Cloud.Audit.V1.AuthenticationInfo.Parser, new[]{ "PrincipalEmail" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Audit.V1.AuthorizationInfo), global::Google.Events.Protobuf.Cloud.Audit.V1.AuthorizationInfo.Parser, new[]{ "Resource", "Permission", "Granted" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Audit.V1.RequestMetadata), global::Google.Events.Protobuf.Cloud.Audit.V1.RequestMetadata.Parser, new[]{ "CallerIp", "CallerSuppliedUserAgent" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// The CloudEvent raised when an audit log entry is created.
  /// </summary>
  public sealed partial class AuditLogCreated : pb::IMessage<AuditLogCreated> {
    private static readonly pb::MessageParser<AuditLogCreated> _parser = new pb::MessageParser<AuditLogCreated>(() => new AuditLogCreated());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AuditLogCreated> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Audit.V1.EventsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditLogCreated() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditLogCreated(AuditLogCreated other) : this() {
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditLogCreated Clone() {
      return new AuditLogCreated(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private global::Google.Events.Protobuf.Cloud.Audit.V1.AuditLogData data_;
    /// <summary>
    /// The data associated with the event.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Audit.V1.AuditLogData Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AuditLogCreated);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AuditLogCreated other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AuditLogCreated other) {
      if (other == null) {
        return;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Events.Protobuf.Cloud.Audit.V1.AuditLogData();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (data_ == null) {
              Data = new global::Google.Events.Protobuf.Cloud.Audit.V1.AuditLogData();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Common audit log format for Google Cloud Platform API operations.
  /// </summary>
  public sealed partial class AuditLogData : pb::IMessage<AuditLogData> {
    private static readonly pb::MessageParser<AuditLogData> _parser = new pb::MessageParser<AuditLogData>(() => new AuditLogData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AuditLogData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Audit.V1.EventsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditLogData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditLogData(AuditLogData other) : this() {
      serviceName_ = other.serviceName_;
      methodName_ = other.methodName_;
      resourceName_ = other.resourceName_;
      numResponseItems_ = other.numResponseItems_;
      status_ = other.status_ != null ? other.status_.Clone() : null;
      authenticationInfo_ = other.authenticationInfo_ != null ? other.authenticationInfo_.Clone() : null;
      authorizationInfo_ = other.authorizationInfo_.Clone();
      requestMetadata_ = other.requestMetadata_ != null ? other.requestMetadata_.Clone() : null;
      request_ = other.request_ != null ? other.request_.Clone() : null;
      response_ = other.response_ != null ? other.response_.Clone() : null;
      serviceData_ = other.serviceData_ != null ? other.serviceData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuditLogData Clone() {
      return new AuditLogData(this);
    }

    /// <summary>Field number for the "service_name" field.</summary>
    public const int ServiceNameFieldNumber = 7;
    private string serviceName_ = "";
    /// <summary>
    /// The name of the API service performing the operation. For example,
    /// `"datastore.googleapis.com"`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ServiceName {
      get { return serviceName_; }
      set {
        serviceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "method_name" field.</summary>
    public const int MethodNameFieldNumber = 8;
    private string methodName_ = "";
    /// <summary>
    /// The name of the service method or operation.
    /// For API calls, this should be the name of the API method.
    /// For example,
    ///
    ///     "google.datastore.v1.Datastore.RunQuery"
    ///     "google.logging.v1.LoggingService.DeleteLog"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MethodName {
      get { return methodName_; }
      set {
        methodName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "resource_name" field.</summary>
    public const int ResourceNameFieldNumber = 11;
    private string resourceName_ = "";
    /// <summary>
    /// The resource or collection that is the target of the operation.
    /// The name is a scheme-less URI, not including the API service name.
    /// For example:
    ///
    ///     "shelves/SHELF_ID/books"
    ///     "shelves/SHELF_ID/books/BOOK_ID"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ResourceName {
      get { return resourceName_; }
      set {
        resourceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_response_items" field.</summary>
    public const int NumResponseItemsFieldNumber = 12;
    private long numResponseItems_;
    /// <summary>
    /// The number of items returned from a List or Query API method,
    /// if applicable.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long NumResponseItems {
      get { return numResponseItems_; }
      set {
        numResponseItems_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::Google.Rpc.Status status_;
    /// <summary>
    /// The status of the overall operation.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Rpc.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "authentication_info" field.</summary>
    public const int AuthenticationInfoFieldNumber = 3;
    private global::Google.Events.Protobuf.Cloud.Audit.V1.AuthenticationInfo authenticationInfo_;
    /// <summary>
    /// Authentication information.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Audit.V1.AuthenticationInfo AuthenticationInfo {
      get { return authenticationInfo_; }
      set {
        authenticationInfo_ = value;
      }
    }

    /// <summary>Field number for the "authorization_info" field.</summary>
    public const int AuthorizationInfoFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Google.Events.Protobuf.Cloud.Audit.V1.AuthorizationInfo> _repeated_authorizationInfo_codec
        = pb::FieldCodec.ForMessage(74, global::Google.Events.Protobuf.Cloud.Audit.V1.AuthorizationInfo.Parser);
    private readonly pbc::RepeatedField<global::Google.Events.Protobuf.Cloud.Audit.V1.AuthorizationInfo> authorizationInfo_ = new pbc::RepeatedField<global::Google.Events.Protobuf.Cloud.Audit.V1.AuthorizationInfo>();
    /// <summary>
    /// Authorization information. If there are multiple
    /// resources or permissions involved, then there is
    /// one AuthorizationInfo element for each {resource, permission} tuple.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Google.Events.Protobuf.Cloud.Audit.V1.AuthorizationInfo> AuthorizationInfo {
      get { return authorizationInfo_; }
    }

    /// <summary>Field number for the "request_metadata" field.</summary>
    public const int RequestMetadataFieldNumber = 4;
    private global::Google.Events.Protobuf.Cloud.Audit.V1.RequestMetadata requestMetadata_;
    /// <summary>
    /// Metadata about the operation.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Audit.V1.RequestMetadata RequestMetadata {
      get { return requestMetadata_; }
      set {
        requestMetadata_ = value;
      }
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 16;
    private global::Google.Protobuf.WellKnownTypes.Struct request_;
    /// <summary>
    /// The operation request. This may not include all request parameters,
    /// such as those that are too large, privacy-sensitive, or duplicated
    /// elsewhere in the log record.
    /// It should never include user-generated data, such as file contents.
    /// When the JSON object represented here has a proto equivalent, the proto
    /// name will be indicated in the `@type` property.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Struct Request {
      get { return request_; }
      set {
        request_ = value;
      }
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 17;
    private global::Google.Protobuf.WellKnownTypes.Struct response_;
    /// <summary>
    /// The operation response. This may not include all response elements,
    /// such as those that are too large, privacy-sensitive, or duplicated
    /// elsewhere in the log record.
    /// It should never include user-generated data, such as file contents.
    /// When the JSON object represented here has a proto equivalent, the proto
    /// name will be indicated in the `@type` property.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Struct Response {
      get { return response_; }
      set {
        response_ = value;
      }
    }

    /// <summary>Field number for the "service_data" field.</summary>
    public const int ServiceDataFieldNumber = 15;
    private global::Google.Protobuf.WellKnownTypes.Struct serviceData_;
    /// <summary>
    /// Other service-specific data about the request, response, and other
    /// activities.
    /// When the JSON object represented here has a proto equivalent, the proto
    /// name will be indicated in the `@type` property.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Struct ServiceData {
      get { return serviceData_; }
      set {
        serviceData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AuditLogData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AuditLogData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServiceName != other.ServiceName) return false;
      if (MethodName != other.MethodName) return false;
      if (ResourceName != other.ResourceName) return false;
      if (NumResponseItems != other.NumResponseItems) return false;
      if (!object.Equals(Status, other.Status)) return false;
      if (!object.Equals(AuthenticationInfo, other.AuthenticationInfo)) return false;
      if(!authorizationInfo_.Equals(other.authorizationInfo_)) return false;
      if (!object.Equals(RequestMetadata, other.RequestMetadata)) return false;
      if (!object.Equals(Request, other.Request)) return false;
      if (!object.Equals(Response, other.Response)) return false;
      if (!object.Equals(ServiceData, other.ServiceData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ServiceName.Length != 0) hash ^= ServiceName.GetHashCode();
      if (MethodName.Length != 0) hash ^= MethodName.GetHashCode();
      if (ResourceName.Length != 0) hash ^= ResourceName.GetHashCode();
      if (NumResponseItems != 0L) hash ^= NumResponseItems.GetHashCode();
      if (status_ != null) hash ^= Status.GetHashCode();
      if (authenticationInfo_ != null) hash ^= AuthenticationInfo.GetHashCode();
      hash ^= authorizationInfo_.GetHashCode();
      if (requestMetadata_ != null) hash ^= RequestMetadata.GetHashCode();
      if (request_ != null) hash ^= Request.GetHashCode();
      if (response_ != null) hash ^= Response.GetHashCode();
      if (serviceData_ != null) hash ^= ServiceData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (status_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Status);
      }
      if (authenticationInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AuthenticationInfo);
      }
      if (requestMetadata_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(RequestMetadata);
      }
      if (ServiceName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ServiceName);
      }
      if (MethodName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(MethodName);
      }
      authorizationInfo_.WriteTo(output, _repeated_authorizationInfo_codec);
      if (ResourceName.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(ResourceName);
      }
      if (NumResponseItems != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(NumResponseItems);
      }
      if (serviceData_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(ServiceData);
      }
      if (request_ != null) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(Request);
      }
      if (response_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(Response);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ServiceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServiceName);
      }
      if (MethodName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MethodName);
      }
      if (ResourceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResourceName);
      }
      if (NumResponseItems != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(NumResponseItems);
      }
      if (status_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Status);
      }
      if (authenticationInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AuthenticationInfo);
      }
      size += authorizationInfo_.CalculateSize(_repeated_authorizationInfo_codec);
      if (requestMetadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RequestMetadata);
      }
      if (request_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Request);
      }
      if (response_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      if (serviceData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServiceData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AuditLogData other) {
      if (other == null) {
        return;
      }
      if (other.ServiceName.Length != 0) {
        ServiceName = other.ServiceName;
      }
      if (other.MethodName.Length != 0) {
        MethodName = other.MethodName;
      }
      if (other.ResourceName.Length != 0) {
        ResourceName = other.ResourceName;
      }
      if (other.NumResponseItems != 0L) {
        NumResponseItems = other.NumResponseItems;
      }
      if (other.status_ != null) {
        if (status_ == null) {
          Status = new global::Google.Rpc.Status();
        }
        Status.MergeFrom(other.Status);
      }
      if (other.authenticationInfo_ != null) {
        if (authenticationInfo_ == null) {
          AuthenticationInfo = new global::Google.Events.Protobuf.Cloud.Audit.V1.AuthenticationInfo();
        }
        AuthenticationInfo.MergeFrom(other.AuthenticationInfo);
      }
      authorizationInfo_.Add(other.authorizationInfo_);
      if (other.requestMetadata_ != null) {
        if (requestMetadata_ == null) {
          RequestMetadata = new global::Google.Events.Protobuf.Cloud.Audit.V1.RequestMetadata();
        }
        RequestMetadata.MergeFrom(other.RequestMetadata);
      }
      if (other.request_ != null) {
        if (request_ == null) {
          Request = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        Request.MergeFrom(other.Request);
      }
      if (other.response_ != null) {
        if (response_ == null) {
          Response = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        Response.MergeFrom(other.Response);
      }
      if (other.serviceData_ != null) {
        if (serviceData_ == null) {
          ServiceData = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        ServiceData.MergeFrom(other.ServiceData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            if (status_ == null) {
              Status = new global::Google.Rpc.Status();
            }
            input.ReadMessage(Status);
            break;
          }
          case 26: {
            if (authenticationInfo_ == null) {
              AuthenticationInfo = new global::Google.Events.Protobuf.Cloud.Audit.V1.AuthenticationInfo();
            }
            input.ReadMessage(AuthenticationInfo);
            break;
          }
          case 34: {
            if (requestMetadata_ == null) {
              RequestMetadata = new global::Google.Events.Protobuf.Cloud.Audit.V1.RequestMetadata();
            }
            input.ReadMessage(RequestMetadata);
            break;
          }
          case 58: {
            ServiceName = input.ReadString();
            break;
          }
          case 66: {
            MethodName = input.ReadString();
            break;
          }
          case 74: {
            authorizationInfo_.AddEntriesFrom(input, _repeated_authorizationInfo_codec);
            break;
          }
          case 90: {
            ResourceName = input.ReadString();
            break;
          }
          case 96: {
            NumResponseItems = input.ReadInt64();
            break;
          }
          case 122: {
            if (serviceData_ == null) {
              ServiceData = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(ServiceData);
            break;
          }
          case 130: {
            if (request_ == null) {
              Request = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(Request);
            break;
          }
          case 138: {
            if (response_ == null) {
              Response = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(Response);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Authentication information for the operation.
  /// </summary>
  public sealed partial class AuthenticationInfo : pb::IMessage<AuthenticationInfo> {
    private static readonly pb::MessageParser<AuthenticationInfo> _parser = new pb::MessageParser<AuthenticationInfo>(() => new AuthenticationInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AuthenticationInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Audit.V1.EventsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuthenticationInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuthenticationInfo(AuthenticationInfo other) : this() {
      principalEmail_ = other.principalEmail_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuthenticationInfo Clone() {
      return new AuthenticationInfo(this);
    }

    /// <summary>Field number for the "principal_email" field.</summary>
    public const int PrincipalEmailFieldNumber = 1;
    private string principalEmail_ = "";
    /// <summary>
    /// The email address of the authenticated user making the request.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PrincipalEmail {
      get { return principalEmail_; }
      set {
        principalEmail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AuthenticationInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AuthenticationInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PrincipalEmail != other.PrincipalEmail) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PrincipalEmail.Length != 0) hash ^= PrincipalEmail.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PrincipalEmail.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PrincipalEmail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PrincipalEmail.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PrincipalEmail);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AuthenticationInfo other) {
      if (other == null) {
        return;
      }
      if (other.PrincipalEmail.Length != 0) {
        PrincipalEmail = other.PrincipalEmail;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PrincipalEmail = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Authorization information for the operation.
  /// </summary>
  public sealed partial class AuthorizationInfo : pb::IMessage<AuthorizationInfo> {
    private static readonly pb::MessageParser<AuthorizationInfo> _parser = new pb::MessageParser<AuthorizationInfo>(() => new AuthorizationInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AuthorizationInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Audit.V1.EventsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuthorizationInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuthorizationInfo(AuthorizationInfo other) : this() {
      resource_ = other.resource_;
      permission_ = other.permission_;
      granted_ = other.granted_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuthorizationInfo Clone() {
      return new AuthorizationInfo(this);
    }

    /// <summary>Field number for the "resource" field.</summary>
    public const int ResourceFieldNumber = 1;
    private string resource_ = "";
    /// <summary>
    /// The resource being accessed, as a REST-style string. For example:
    ///
    ///     bigquery.googlapis.com/projects/PROJECTID/datasets/DATASETID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Resource {
      get { return resource_; }
      set {
        resource_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "permission" field.</summary>
    public const int PermissionFieldNumber = 2;
    private string permission_ = "";
    /// <summary>
    /// The required IAM permission.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Permission {
      get { return permission_; }
      set {
        permission_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "granted" field.</summary>
    public const int GrantedFieldNumber = 3;
    private bool granted_;
    /// <summary>
    /// Whether or not authorization for `resource` and `permission`
    /// was granted.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Granted {
      get { return granted_; }
      set {
        granted_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AuthorizationInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AuthorizationInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Resource != other.Resource) return false;
      if (Permission != other.Permission) return false;
      if (Granted != other.Granted) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Resource.Length != 0) hash ^= Resource.GetHashCode();
      if (Permission.Length != 0) hash ^= Permission.GetHashCode();
      if (Granted != false) hash ^= Granted.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Resource.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Resource);
      }
      if (Permission.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Permission);
      }
      if (Granted != false) {
        output.WriteRawTag(24);
        output.WriteBool(Granted);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Resource.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Resource);
      }
      if (Permission.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Permission);
      }
      if (Granted != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AuthorizationInfo other) {
      if (other == null) {
        return;
      }
      if (other.Resource.Length != 0) {
        Resource = other.Resource;
      }
      if (other.Permission.Length != 0) {
        Permission = other.Permission;
      }
      if (other.Granted != false) {
        Granted = other.Granted;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Resource = input.ReadString();
            break;
          }
          case 18: {
            Permission = input.ReadString();
            break;
          }
          case 24: {
            Granted = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Metadata about the request.
  /// </summary>
  public sealed partial class RequestMetadata : pb::IMessage<RequestMetadata> {
    private static readonly pb::MessageParser<RequestMetadata> _parser = new pb::MessageParser<RequestMetadata>(() => new RequestMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Audit.V1.EventsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestMetadata(RequestMetadata other) : this() {
      callerIp_ = other.callerIp_;
      callerSuppliedUserAgent_ = other.callerSuppliedUserAgent_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestMetadata Clone() {
      return new RequestMetadata(this);
    }

    /// <summary>Field number for the "caller_ip" field.</summary>
    public const int CallerIpFieldNumber = 1;
    private string callerIp_ = "";
    /// <summary>
    /// The IP address of the caller.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CallerIp {
      get { return callerIp_; }
      set {
        callerIp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "caller_supplied_user_agent" field.</summary>
    public const int CallerSuppliedUserAgentFieldNumber = 2;
    private string callerSuppliedUserAgent_ = "";
    /// <summary>
    /// The user agent of the caller.
    /// This information is not authenticated and should be treated accordingly.
    /// For example:
    ///
    /// +   `google-api-python-client/1.4.0`:
    ///     The request was made by the Google API client for Python.
    /// +   `Cloud SDK Command Line Tool apitools-client/1.0 gcloud/0.9.62`:
    ///     The request was made by the Google Cloud SDK CLI (gcloud).
    /// +   `AppEngine-Google; (+http://code.google.com/appengine; appid:
    /// s~my-project`:
    ///     The request was made from the `my-project` App Engine app.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CallerSuppliedUserAgent {
      get { return callerSuppliedUserAgent_; }
      set {
        callerSuppliedUserAgent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CallerIp != other.CallerIp) return false;
      if (CallerSuppliedUserAgent != other.CallerSuppliedUserAgent) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CallerIp.Length != 0) hash ^= CallerIp.GetHashCode();
      if (CallerSuppliedUserAgent.Length != 0) hash ^= CallerSuppliedUserAgent.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CallerIp.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CallerIp);
      }
      if (CallerSuppliedUserAgent.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CallerSuppliedUserAgent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CallerIp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CallerIp);
      }
      if (CallerSuppliedUserAgent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CallerSuppliedUserAgent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestMetadata other) {
      if (other == null) {
        return;
      }
      if (other.CallerIp.Length != 0) {
        CallerIp = other.CallerIp;
      }
      if (other.CallerSuppliedUserAgent.Length != 0) {
        CallerSuppliedUserAgent = other.CallerSuppliedUserAgent;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CallerIp = input.ReadString();
            break;
          }
          case 18: {
            CallerSuppliedUserAgent = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
