// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/events/cloud/firestore/v1/events.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Events.Protobuf.Cloud.Firestore.V1 {

  /// <summary>Holder for reflection information generated from google/events/cloud/firestore/v1/events.proto</summary>
  public static partial class EventsReflection {

    #region Descriptor
    /// <summary>File descriptor for google/events/cloud/firestore/v1/events.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1nb29nbGUvZXZlbnRzL2Nsb3VkL2ZpcmVzdG9yZS92MS9ldmVudHMucHJv",
            "dG8SIGdvb2dsZS5ldmVudHMuY2xvdWQuZmlyZXN0b3JlLnYxGh5nb29nbGUv",
            "ZXZlbnRzL2Nsb3VkZXZlbnQucHJvdG8aHGdvb2dsZS9wcm90b2J1Zi9zdHJ1",
            "Y3QucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8aGGdv",
            "b2dsZS90eXBlL2xhdGxuZy5wcm90byKEAQoPRG9jdW1lbnRDcmVhdGVkEkEK",
            "BGRhdGEYASABKAsyMy5nb29nbGUuZXZlbnRzLmNsb3VkLmZpcmVzdG9yZS52",
            "MS5Eb2N1bWVudEV2ZW50RGF0YTouguIJKmdvb2dsZS5jbG91ZC5maXJlc3Rv",
            "cmUuZG9jdW1lbnQudjEuY3JlYXRlZCKEAQoPRG9jdW1lbnRVcGRhdGVkEkEK",
            "BGRhdGEYASABKAsyMy5nb29nbGUuZXZlbnRzLmNsb3VkLmZpcmVzdG9yZS52",
            "MS5Eb2N1bWVudEV2ZW50RGF0YTouguIJKmdvb2dsZS5jbG91ZC5maXJlc3Rv",
            "cmUuZG9jdW1lbnQudjEudXBkYXRlZCKEAQoPRG9jdW1lbnREZWxldGVkEkEK",
            "BGRhdGEYASABKAsyMy5nb29nbGUuZXZlbnRzLmNsb3VkLmZpcmVzdG9yZS52",
            "MS5Eb2N1bWVudEV2ZW50RGF0YTouguIJKmdvb2dsZS5jbG91ZC5maXJlc3Rv",
            "cmUuZG9jdW1lbnQudjEuZGVsZXRlZCKEAQoPRG9jdW1lbnRXcml0dGVuEkEK",
            "BGRhdGEYASABKAsyMy5nb29nbGUuZXZlbnRzLmNsb3VkLmZpcmVzdG9yZS52",
            "MS5Eb2N1bWVudEV2ZW50RGF0YTouguIJKmdvb2dsZS5jbG91ZC5maXJlc3Rv",
            "cmUuZG9jdW1lbnQudjEud3JpdHRlbiLbAgoRRG9jdW1lbnRFdmVudERhdGES",
            "PQoJb2xkX3ZhbHVlGAEgASgLMiouZ29vZ2xlLmV2ZW50cy5jbG91ZC5maXJl",
            "c3RvcmUudjEuRG9jdW1lbnQSQwoLdXBkYXRlX21hc2sYAiABKAsyLi5nb29n",
            "bGUuZXZlbnRzLmNsb3VkLmZpcmVzdG9yZS52MS5Eb2N1bWVudE1hc2sSOQoF",
            "dmFsdWUYAyABKAsyKi5nb29nbGUuZXZlbnRzLmNsb3VkLmZpcmVzdG9yZS52",
            "MS5Eb2N1bWVudBJVCgl3aWxkY2FyZHMYBCADKAsyQi5nb29nbGUuZXZlbnRz",
            "LmNsb3VkLmZpcmVzdG9yZS52MS5Eb2N1bWVudEV2ZW50RGF0YS5XaWxkY2Fy",
            "ZHNFbnRyeRowCg5XaWxkY2FyZHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFs",
            "dWUYAiABKAk6AjgBIiMKDERvY3VtZW50TWFzaxITCgtmaWVsZF9wYXRocxgB",
            "IAMoCSKaAgoIRG9jdW1lbnQSDAoEbmFtZRgBIAEoCRJGCgZmaWVsZHMYAiAD",
            "KAsyNi5nb29nbGUuZXZlbnRzLmNsb3VkLmZpcmVzdG9yZS52MS5Eb2N1bWVu",
            "dC5GaWVsZHNFbnRyeRIvCgtjcmVhdGVfdGltZRgDIAEoCzIaLmdvb2dsZS5w",
            "cm90b2J1Zi5UaW1lc3RhbXASLwoLdXBkYXRlX3RpbWUYBCABKAsyGi5nb29n",
            "bGUucHJvdG9idWYuVGltZXN0YW1wGlYKC0ZpZWxkc0VudHJ5EgsKA2tleRgB",
            "IAEoCRI2CgV2YWx1ZRgCIAEoCzInLmdvb2dsZS5ldmVudHMuY2xvdWQuZmly",
            "ZXN0b3JlLnYxLlZhbHVlOgI4ASLIAwoFVmFsdWUSMAoKbnVsbF92YWx1ZRgL",
            "IAEoDjIaLmdvb2dsZS5wcm90b2J1Zi5OdWxsVmFsdWVIABIXCg1ib29sZWFu",
            "X3ZhbHVlGAEgASgISAASFwoNaW50ZWdlcl92YWx1ZRgCIAEoA0gAEhYKDGRv",
            "dWJsZV92YWx1ZRgDIAEoAUgAEjUKD3RpbWVzdGFtcF92YWx1ZRgKIAEoCzIa",
            "Lmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIABIWCgxzdHJpbmdfdmFsdWUY",
            "ESABKAlIABIVCgtieXRlc192YWx1ZRgSIAEoDEgAEhkKD3JlZmVyZW5jZV92",
            "YWx1ZRgFIAEoCUgAEi4KD2dlb19wb2ludF92YWx1ZRgIIAEoCzITLmdvb2ds",
            "ZS50eXBlLkxhdExuZ0gAEkMKC2FycmF5X3ZhbHVlGAkgASgLMiwuZ29vZ2xl",
            "LmV2ZW50cy5jbG91ZC5maXJlc3RvcmUudjEuQXJyYXlWYWx1ZUgAEj8KCW1h",
            "cF92YWx1ZRgGIAEoCzIqLmdvb2dsZS5ldmVudHMuY2xvdWQuZmlyZXN0b3Jl",
            "LnYxLk1hcFZhbHVlSABCDAoKdmFsdWVfdHlwZSJFCgpBcnJheVZhbHVlEjcK",
            "BnZhbHVlcxgBIAMoCzInLmdvb2dsZS5ldmVudHMuY2xvdWQuZmlyZXN0b3Jl",
            "LnYxLlZhbHVlIqoBCghNYXBWYWx1ZRJGCgZmaWVsZHMYASADKAsyNi5nb29n",
            "bGUuZXZlbnRzLmNsb3VkLmZpcmVzdG9yZS52MS5NYXBWYWx1ZS5GaWVsZHNF",
            "bnRyeRpWCgtGaWVsZHNFbnRyeRILCgNrZXkYASABKAkSNgoFdmFsdWUYAiAB",
            "KAsyJy5nb29nbGUuZXZlbnRzLmNsb3VkLmZpcmVzdG9yZS52MS5WYWx1ZToC",
            "OAFCLKoCKUdvb2dsZS5FdmVudHMuUHJvdG9idWYuQ2xvdWQuRmlyZXN0b3Jl",
            "LlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Events.Protobuf.CloudeventReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Google.Type.LatlngReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentCreated), global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentCreated.Parser, new[]{ "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentUpdated), global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentUpdated.Parser, new[]{ "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentDeleted), global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentDeleted.Parser, new[]{ "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentWritten), global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentWritten.Parser, new[]{ "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData), global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData.Parser, new[]{ "OldValue", "UpdateMask", "Value", "Wildcards" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentMask), global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentMask.Parser, new[]{ "FieldPaths" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Firestore.V1.Document), global::Google.Events.Protobuf.Cloud.Firestore.V1.Document.Parser, new[]{ "Name", "Fields", "CreateTime", "UpdateTime" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Firestore.V1.Value), global::Google.Events.Protobuf.Cloud.Firestore.V1.Value.Parser, new[]{ "NullValue", "BooleanValue", "IntegerValue", "DoubleValue", "TimestampValue", "StringValue", "BytesValue", "ReferenceValue", "GeoPointValue", "ArrayValue", "MapValue" }, new[]{ "ValueType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Firestore.V1.ArrayValue), global::Google.Events.Protobuf.Cloud.Firestore.V1.ArrayValue.Parser, new[]{ "Values" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Firestore.V1.MapValue), global::Google.Events.Protobuf.Cloud.Firestore.V1.MapValue.Parser, new[]{ "Fields" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// The CloudEvent raised when a Firestore document is created.
  /// </summary>
  public sealed partial class DocumentCreated : pb::IMessage<DocumentCreated> {
    private static readonly pb::MessageParser<DocumentCreated> _parser = new pb::MessageParser<DocumentCreated>(() => new DocumentCreated());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DocumentCreated> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Firestore.V1.EventsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentCreated() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentCreated(DocumentCreated other) : this() {
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentCreated Clone() {
      return new DocumentCreated(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData data_;
    /// <summary>
    /// The data associated with the event.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DocumentCreated);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DocumentCreated other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DocumentCreated other) {
      if (other == null) {
        return;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (data_ == null) {
              Data = new global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// The CloudEvent raised when a Firestore document is updated.
  /// </summary>
  public sealed partial class DocumentUpdated : pb::IMessage<DocumentUpdated> {
    private static readonly pb::MessageParser<DocumentUpdated> _parser = new pb::MessageParser<DocumentUpdated>(() => new DocumentUpdated());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DocumentUpdated> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Firestore.V1.EventsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentUpdated() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentUpdated(DocumentUpdated other) : this() {
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentUpdated Clone() {
      return new DocumentUpdated(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData data_;
    /// <summary>
    /// The data associated with the event.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DocumentUpdated);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DocumentUpdated other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DocumentUpdated other) {
      if (other == null) {
        return;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (data_ == null) {
              Data = new global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// The CloudEvent raised when a Firestore document is deleted.
  /// </summary>
  public sealed partial class DocumentDeleted : pb::IMessage<DocumentDeleted> {
    private static readonly pb::MessageParser<DocumentDeleted> _parser = new pb::MessageParser<DocumentDeleted>(() => new DocumentDeleted());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DocumentDeleted> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Firestore.V1.EventsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentDeleted() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentDeleted(DocumentDeleted other) : this() {
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentDeleted Clone() {
      return new DocumentDeleted(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData data_;
    /// <summary>
    /// The data associated with the event.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DocumentDeleted);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DocumentDeleted other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DocumentDeleted other) {
      if (other == null) {
        return;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (data_ == null) {
              Data = new global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// The CloudEvent raised when a Firestore document is created, updated or deleted.
  /// </summary>
  public sealed partial class DocumentWritten : pb::IMessage<DocumentWritten> {
    private static readonly pb::MessageParser<DocumentWritten> _parser = new pb::MessageParser<DocumentWritten>(() => new DocumentWritten());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DocumentWritten> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Firestore.V1.EventsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentWritten() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentWritten(DocumentWritten other) : this() {
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentWritten Clone() {
      return new DocumentWritten(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData data_;
    /// <summary>
    /// The data associated with the event.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DocumentWritten);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DocumentWritten other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DocumentWritten other) {
      if (other == null) {
        return;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (data_ == null) {
              Data = new global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentEventData();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// The data within all Firestore document events.
  /// </summary>
  public sealed partial class DocumentEventData : pb::IMessage<DocumentEventData> {
    private static readonly pb::MessageParser<DocumentEventData> _parser = new pb::MessageParser<DocumentEventData>(() => new DocumentEventData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DocumentEventData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Firestore.V1.EventsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentEventData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentEventData(DocumentEventData other) : this() {
      oldValue_ = other.oldValue_ != null ? other.oldValue_.Clone() : null;
      updateMask_ = other.updateMask_ != null ? other.updateMask_.Clone() : null;
      value_ = other.value_ != null ? other.value_.Clone() : null;
      wildcards_ = other.wildcards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentEventData Clone() {
      return new DocumentEventData(this);
    }

    /// <summary>Field number for the "old_value" field.</summary>
    public const int OldValueFieldNumber = 1;
    private global::Google.Events.Protobuf.Cloud.Firestore.V1.Document oldValue_;
    /// <summary>
    /// A Document object containing a pre-operation document snapshot.
    /// This is only populated for update and delete events.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Firestore.V1.Document OldValue {
      get { return oldValue_; }
      set {
        oldValue_ = value;
      }
    }

    /// <summary>Field number for the "update_mask" field.</summary>
    public const int UpdateMaskFieldNumber = 2;
    private global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentMask updateMask_;
    /// <summary>
    /// A DocumentMask object that lists changed fields.
    /// This is only populated for update events.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentMask UpdateMask {
      get { return updateMask_; }
      set {
        updateMask_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 3;
    private global::Google.Events.Protobuf.Cloud.Firestore.V1.Document value_;
    /// <summary>
    /// A Document object containing a post-operation document snapshot.
    /// This is not populated for delete events. (TODO: check this!)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Firestore.V1.Document Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    /// <summary>Field number for the "wildcards" field.</summary>
    public const int WildcardsFieldNumber = 4;
    private static readonly pbc::MapField<string, string>.Codec _map_wildcards_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 34);
    private readonly pbc::MapField<string, string> wildcards_ = new pbc::MapField<string, string>();
    /// <summary>
    /// The matches from wildcards specified in the event subscription, to the
    /// values of those wildcards in the document name. For example,
    /// a subscription to
    /// `/projects/my_project/databases/(default)/documents/users/{username}`
    /// matching a document with name
    /// `/projects/my_project/databases/(default)/documents/users/marie`
    /// would result in a mapping of `'username': 'marie'`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Wildcards {
      get { return wildcards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DocumentEventData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DocumentEventData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OldValue, other.OldValue)) return false;
      if (!object.Equals(UpdateMask, other.UpdateMask)) return false;
      if (!object.Equals(Value, other.Value)) return false;
      if (!Wildcards.Equals(other.Wildcards)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (oldValue_ != null) hash ^= OldValue.GetHashCode();
      if (updateMask_ != null) hash ^= UpdateMask.GetHashCode();
      if (value_ != null) hash ^= Value.GetHashCode();
      hash ^= Wildcards.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (oldValue_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OldValue);
      }
      if (updateMask_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UpdateMask);
      }
      if (value_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Value);
      }
      wildcards_.WriteTo(output, _map_wildcards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (oldValue_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OldValue);
      }
      if (updateMask_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateMask);
      }
      if (value_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Value);
      }
      size += wildcards_.CalculateSize(_map_wildcards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DocumentEventData other) {
      if (other == null) {
        return;
      }
      if (other.oldValue_ != null) {
        if (oldValue_ == null) {
          OldValue = new global::Google.Events.Protobuf.Cloud.Firestore.V1.Document();
        }
        OldValue.MergeFrom(other.OldValue);
      }
      if (other.updateMask_ != null) {
        if (updateMask_ == null) {
          UpdateMask = new global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentMask();
        }
        UpdateMask.MergeFrom(other.UpdateMask);
      }
      if (other.value_ != null) {
        if (value_ == null) {
          Value = new global::Google.Events.Protobuf.Cloud.Firestore.V1.Document();
        }
        Value.MergeFrom(other.Value);
      }
      wildcards_.Add(other.wildcards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (oldValue_ == null) {
              OldValue = new global::Google.Events.Protobuf.Cloud.Firestore.V1.Document();
            }
            input.ReadMessage(OldValue);
            break;
          }
          case 18: {
            if (updateMask_ == null) {
              UpdateMask = new global::Google.Events.Protobuf.Cloud.Firestore.V1.DocumentMask();
            }
            input.ReadMessage(UpdateMask);
            break;
          }
          case 26: {
            if (value_ == null) {
              Value = new global::Google.Events.Protobuf.Cloud.Firestore.V1.Document();
            }
            input.ReadMessage(Value);
            break;
          }
          case 34: {
            wildcards_.AddEntriesFrom(input, _map_wildcards_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// A set of field paths on a document.
  /// </summary>
  public sealed partial class DocumentMask : pb::IMessage<DocumentMask> {
    private static readonly pb::MessageParser<DocumentMask> _parser = new pb::MessageParser<DocumentMask>(() => new DocumentMask());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DocumentMask> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Firestore.V1.EventsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentMask() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentMask(DocumentMask other) : this() {
      fieldPaths_ = other.fieldPaths_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DocumentMask Clone() {
      return new DocumentMask(this);
    }

    /// <summary>Field number for the "field_paths" field.</summary>
    public const int FieldPathsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_fieldPaths_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> fieldPaths_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// The list of field paths in the mask.
    /// See [Document.fields][google.cloud.firestore.v1.events.Document.fields]
    /// for a field path syntax reference.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> FieldPaths {
      get { return fieldPaths_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DocumentMask);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DocumentMask other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!fieldPaths_.Equals(other.fieldPaths_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= fieldPaths_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      fieldPaths_.WriteTo(output, _repeated_fieldPaths_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += fieldPaths_.CalculateSize(_repeated_fieldPaths_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DocumentMask other) {
      if (other == null) {
        return;
      }
      fieldPaths_.Add(other.fieldPaths_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            fieldPaths_.AddEntriesFrom(input, _repeated_fieldPaths_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// A Firestore document.
  /// </summary>
  public sealed partial class Document : pb::IMessage<Document> {
    private static readonly pb::MessageParser<Document> _parser = new pb::MessageParser<Document>(() => new Document());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Document> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Firestore.V1.EventsReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Document() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Document(Document other) : this() {
      name_ = other.name_;
      fields_ = other.fields_.Clone();
      createTime_ = other.createTime_ != null ? other.createTime_.Clone() : null;
      updateTime_ = other.updateTime_ != null ? other.updateTime_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Document Clone() {
      return new Document(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// The resource name of the document, for example
    /// `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fields" field.</summary>
    public const int FieldsFieldNumber = 2;
    private static readonly pbc::MapField<string, global::Google.Events.Protobuf.Cloud.Firestore.V1.Value>.Codec _map_fields_codec
        = new pbc::MapField<string, global::Google.Events.Protobuf.Cloud.Firestore.V1.Value>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Google.Events.Protobuf.Cloud.Firestore.V1.Value.Parser), 18);
    private readonly pbc::MapField<string, global::Google.Events.Protobuf.Cloud.Firestore.V1.Value> fields_ = new pbc::MapField<string, global::Google.Events.Protobuf.Cloud.Firestore.V1.Value>();
    /// <summary>
    /// The document's fields.
    ///
    /// The map keys represent field names.
    ///
    /// A simple field name contains only characters `a` to `z`, `A` to `Z`,
    /// `0` to `9`, or `_`, and must not start with `0` to `9`. For example,
    /// `foo_bar_17`.
    ///
    /// Field names matching the regular expression `__.*__` are reserved. Reserved
    /// field names are forbidden except in certain documented contexts. The map
    /// keys, represented as UTF-8, must not exceed 1,500 bytes and cannot be
    /// empty.
    ///
    /// Field paths may be used in other contexts to refer to structured fields
    /// defined here. For `map_value`, the field path is represented by the simple
    /// or quoted field names of the containing fields, delimited by `.`. For
    /// example, the structured field
    /// `"foo" : { map_value: { "x&amp;y" : { string_value: "hello" }}}` would be
    /// represented by the field path `foo.x&amp;y`.
    ///
    /// Within a field path, a quoted field name starts and ends with `` ` `` and
    /// may contain any character. Some characters, including `` ` ``, must be
    /// escaped using a `\`. For example, `` `x&amp;y` `` represents `x&amp;y` and
    /// `` `bak\`tik` `` represents `` bak`tik ``.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::Google.Events.Protobuf.Cloud.Firestore.V1.Value> Fields {
      get { return fields_; }
    }

    /// <summary>Field number for the "create_time" field.</summary>
    public const int CreateTimeFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createTime_;
    /// <summary>
    /// The time at which the document was created.
    ///
    /// This value increases monotonically when a document is deleted then
    /// recreated. It can also be compared to values from other documents and
    /// the `read_time` of a query.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreateTime {
      get { return createTime_; }
      set {
        createTime_ = value;
      }
    }

    /// <summary>Field number for the "update_time" field.</summary>
    public const int UpdateTimeFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp updateTime_;
    /// <summary>
    /// The time at which the document was last changed.
    ///
    /// This value is initially set to the `create_time` then increases
    /// monotonically with each change to the document. It can also be
    /// compared to values from other documents and the `read_time` of a query.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp UpdateTime {
      get { return updateTime_; }
      set {
        updateTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Document);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Document other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!Fields.Equals(other.Fields)) return false;
      if (!object.Equals(CreateTime, other.CreateTime)) return false;
      if (!object.Equals(UpdateTime, other.UpdateTime)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      hash ^= Fields.GetHashCode();
      if (createTime_ != null) hash ^= CreateTime.GetHashCode();
      if (updateTime_ != null) hash ^= UpdateTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      fields_.WriteTo(output, _map_fields_codec);
      if (createTime_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CreateTime);
      }
      if (updateTime_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(UpdateTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      size += fields_.CalculateSize(_map_fields_codec);
      if (createTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreateTime);
      }
      if (updateTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Document other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      fields_.Add(other.fields_);
      if (other.createTime_ != null) {
        if (createTime_ == null) {
          CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreateTime.MergeFrom(other.CreateTime);
      }
      if (other.updateTime_ != null) {
        if (updateTime_ == null) {
          UpdateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        UpdateTime.MergeFrom(other.UpdateTime);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            fields_.AddEntriesFrom(input, _map_fields_codec);
            break;
          }
          case 26: {
            if (createTime_ == null) {
              CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateTime);
            break;
          }
          case 34: {
            if (updateTime_ == null) {
              UpdateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(UpdateTime);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// A message that can hold any of the supported value types.
  /// </summary>
  public sealed partial class Value : pb::IMessage<Value> {
    private static readonly pb::MessageParser<Value> _parser = new pb::MessageParser<Value>(() => new Value());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Value> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Firestore.V1.EventsReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Value() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Value(Value other) : this() {
      switch (other.ValueTypeCase) {
        case ValueTypeOneofCase.NullValue:
          NullValue = other.NullValue;
          break;
        case ValueTypeOneofCase.BooleanValue:
          BooleanValue = other.BooleanValue;
          break;
        case ValueTypeOneofCase.IntegerValue:
          IntegerValue = other.IntegerValue;
          break;
        case ValueTypeOneofCase.DoubleValue:
          DoubleValue = other.DoubleValue;
          break;
        case ValueTypeOneofCase.TimestampValue:
          TimestampValue = other.TimestampValue.Clone();
          break;
        case ValueTypeOneofCase.StringValue:
          StringValue = other.StringValue;
          break;
        case ValueTypeOneofCase.BytesValue:
          BytesValue = other.BytesValue;
          break;
        case ValueTypeOneofCase.ReferenceValue:
          ReferenceValue = other.ReferenceValue;
          break;
        case ValueTypeOneofCase.GeoPointValue:
          GeoPointValue = other.GeoPointValue.Clone();
          break;
        case ValueTypeOneofCase.ArrayValue:
          ArrayValue = other.ArrayValue.Clone();
          break;
        case ValueTypeOneofCase.MapValue:
          MapValue = other.MapValue.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Value Clone() {
      return new Value(this);
    }

    /// <summary>Field number for the "null_value" field.</summary>
    public const int NullValueFieldNumber = 11;
    /// <summary>
    /// A null value.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.NullValue NullValue {
      get { return valueTypeCase_ == ValueTypeOneofCase.NullValue ? (global::Google.Protobuf.WellKnownTypes.NullValue) valueType_ : global::Google.Protobuf.WellKnownTypes.NullValue.NullValue; }
      set {
        valueType_ = value;
        valueTypeCase_ = ValueTypeOneofCase.NullValue;
      }
    }

    /// <summary>Field number for the "boolean_value" field.</summary>
    public const int BooleanValueFieldNumber = 1;
    /// <summary>
    /// A boolean value.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool BooleanValue {
      get { return valueTypeCase_ == ValueTypeOneofCase.BooleanValue ? (bool) valueType_ : false; }
      set {
        valueType_ = value;
        valueTypeCase_ = ValueTypeOneofCase.BooleanValue;
      }
    }

    /// <summary>Field number for the "integer_value" field.</summary>
    public const int IntegerValueFieldNumber = 2;
    /// <summary>
    /// An integer value.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long IntegerValue {
      get { return valueTypeCase_ == ValueTypeOneofCase.IntegerValue ? (long) valueType_ : 0L; }
      set {
        valueType_ = value;
        valueTypeCase_ = ValueTypeOneofCase.IntegerValue;
      }
    }

    /// <summary>Field number for the "double_value" field.</summary>
    public const int DoubleValueFieldNumber = 3;
    /// <summary>
    /// A double value.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double DoubleValue {
      get { return valueTypeCase_ == ValueTypeOneofCase.DoubleValue ? (double) valueType_ : 0D; }
      set {
        valueType_ = value;
        valueTypeCase_ = ValueTypeOneofCase.DoubleValue;
      }
    }

    /// <summary>Field number for the "timestamp_value" field.</summary>
    public const int TimestampValueFieldNumber = 10;
    /// <summary>
    /// A timestamp value.
    ///
    /// Precise only to microseconds. When stored, any additional precision is
    /// rounded down.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimestampValue {
      get { return valueTypeCase_ == ValueTypeOneofCase.TimestampValue ? (global::Google.Protobuf.WellKnownTypes.Timestamp) valueType_ : null; }
      set {
        valueType_ = value;
        valueTypeCase_ = value == null ? ValueTypeOneofCase.None : ValueTypeOneofCase.TimestampValue;
      }
    }

    /// <summary>Field number for the "string_value" field.</summary>
    public const int StringValueFieldNumber = 17;
    /// <summary>
    /// A string value.
    ///
    /// The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
    /// Only the first 1,500 bytes of the UTF-8 representation are considered by
    /// queries.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StringValue {
      get { return valueTypeCase_ == ValueTypeOneofCase.StringValue ? (string) valueType_ : ""; }
      set {
        valueType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        valueTypeCase_ = ValueTypeOneofCase.StringValue;
      }
    }

    /// <summary>Field number for the "bytes_value" field.</summary>
    public const int BytesValueFieldNumber = 18;
    /// <summary>
    /// A bytes value.
    ///
    /// Must not exceed 1 MiB - 89 bytes.
    /// Only the first 1,500 bytes are considered by queries.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString BytesValue {
      get { return valueTypeCase_ == ValueTypeOneofCase.BytesValue ? (pb::ByteString) valueType_ : pb::ByteString.Empty; }
      set {
        valueType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        valueTypeCase_ = ValueTypeOneofCase.BytesValue;
      }
    }

    /// <summary>Field number for the "reference_value" field.</summary>
    public const int ReferenceValueFieldNumber = 5;
    /// <summary>
    /// A reference to a document. For example:
    /// `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ReferenceValue {
      get { return valueTypeCase_ == ValueTypeOneofCase.ReferenceValue ? (string) valueType_ : ""; }
      set {
        valueType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        valueTypeCase_ = ValueTypeOneofCase.ReferenceValue;
      }
    }

    /// <summary>Field number for the "geo_point_value" field.</summary>
    public const int GeoPointValueFieldNumber = 8;
    /// <summary>
    /// A geo point value representing a point on the surface of Earth.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Type.LatLng GeoPointValue {
      get { return valueTypeCase_ == ValueTypeOneofCase.GeoPointValue ? (global::Google.Type.LatLng) valueType_ : null; }
      set {
        valueType_ = value;
        valueTypeCase_ = value == null ? ValueTypeOneofCase.None : ValueTypeOneofCase.GeoPointValue;
      }
    }

    /// <summary>Field number for the "array_value" field.</summary>
    public const int ArrayValueFieldNumber = 9;
    /// <summary>
    /// An array value.
    ///
    /// Cannot directly contain another array value, though can contain an
    /// map which contains another array.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Firestore.V1.ArrayValue ArrayValue {
      get { return valueTypeCase_ == ValueTypeOneofCase.ArrayValue ? (global::Google.Events.Protobuf.Cloud.Firestore.V1.ArrayValue) valueType_ : null; }
      set {
        valueType_ = value;
        valueTypeCase_ = value == null ? ValueTypeOneofCase.None : ValueTypeOneofCase.ArrayValue;
      }
    }

    /// <summary>Field number for the "map_value" field.</summary>
    public const int MapValueFieldNumber = 6;
    /// <summary>
    /// A map value.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Events.Protobuf.Cloud.Firestore.V1.MapValue MapValue {
      get { return valueTypeCase_ == ValueTypeOneofCase.MapValue ? (global::Google.Events.Protobuf.Cloud.Firestore.V1.MapValue) valueType_ : null; }
      set {
        valueType_ = value;
        valueTypeCase_ = value == null ? ValueTypeOneofCase.None : ValueTypeOneofCase.MapValue;
      }
    }

    private object valueType_;
    /// <summary>Enum of possible cases for the "value_type" oneof.</summary>
    public enum ValueTypeOneofCase {
      None = 0,
      NullValue = 11,
      BooleanValue = 1,
      IntegerValue = 2,
      DoubleValue = 3,
      TimestampValue = 10,
      StringValue = 17,
      BytesValue = 18,
      ReferenceValue = 5,
      GeoPointValue = 8,
      ArrayValue = 9,
      MapValue = 6,
    }
    private ValueTypeOneofCase valueTypeCase_ = ValueTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValueTypeOneofCase ValueTypeCase {
      get { return valueTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearValueType() {
      valueTypeCase_ = ValueTypeOneofCase.None;
      valueType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Value);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Value other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NullValue != other.NullValue) return false;
      if (BooleanValue != other.BooleanValue) return false;
      if (IntegerValue != other.IntegerValue) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DoubleValue, other.DoubleValue)) return false;
      if (!object.Equals(TimestampValue, other.TimestampValue)) return false;
      if (StringValue != other.StringValue) return false;
      if (BytesValue != other.BytesValue) return false;
      if (ReferenceValue != other.ReferenceValue) return false;
      if (!object.Equals(GeoPointValue, other.GeoPointValue)) return false;
      if (!object.Equals(ArrayValue, other.ArrayValue)) return false;
      if (!object.Equals(MapValue, other.MapValue)) return false;
      if (ValueTypeCase != other.ValueTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (valueTypeCase_ == ValueTypeOneofCase.NullValue) hash ^= NullValue.GetHashCode();
      if (valueTypeCase_ == ValueTypeOneofCase.BooleanValue) hash ^= BooleanValue.GetHashCode();
      if (valueTypeCase_ == ValueTypeOneofCase.IntegerValue) hash ^= IntegerValue.GetHashCode();
      if (valueTypeCase_ == ValueTypeOneofCase.DoubleValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DoubleValue);
      if (valueTypeCase_ == ValueTypeOneofCase.TimestampValue) hash ^= TimestampValue.GetHashCode();
      if (valueTypeCase_ == ValueTypeOneofCase.StringValue) hash ^= StringValue.GetHashCode();
      if (valueTypeCase_ == ValueTypeOneofCase.BytesValue) hash ^= BytesValue.GetHashCode();
      if (valueTypeCase_ == ValueTypeOneofCase.ReferenceValue) hash ^= ReferenceValue.GetHashCode();
      if (valueTypeCase_ == ValueTypeOneofCase.GeoPointValue) hash ^= GeoPointValue.GetHashCode();
      if (valueTypeCase_ == ValueTypeOneofCase.ArrayValue) hash ^= ArrayValue.GetHashCode();
      if (valueTypeCase_ == ValueTypeOneofCase.MapValue) hash ^= MapValue.GetHashCode();
      hash ^= (int) valueTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (valueTypeCase_ == ValueTypeOneofCase.BooleanValue) {
        output.WriteRawTag(8);
        output.WriteBool(BooleanValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.IntegerValue) {
        output.WriteRawTag(16);
        output.WriteInt64(IntegerValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.DoubleValue) {
        output.WriteRawTag(25);
        output.WriteDouble(DoubleValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.ReferenceValue) {
        output.WriteRawTag(42);
        output.WriteString(ReferenceValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.MapValue) {
        output.WriteRawTag(50);
        output.WriteMessage(MapValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.GeoPointValue) {
        output.WriteRawTag(66);
        output.WriteMessage(GeoPointValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.ArrayValue) {
        output.WriteRawTag(74);
        output.WriteMessage(ArrayValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.TimestampValue) {
        output.WriteRawTag(82);
        output.WriteMessage(TimestampValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.NullValue) {
        output.WriteRawTag(88);
        output.WriteEnum((int) NullValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.StringValue) {
        output.WriteRawTag(138, 1);
        output.WriteString(StringValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.BytesValue) {
        output.WriteRawTag(146, 1);
        output.WriteBytes(BytesValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (valueTypeCase_ == ValueTypeOneofCase.NullValue) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) NullValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.BooleanValue) {
        size += 1 + 1;
      }
      if (valueTypeCase_ == ValueTypeOneofCase.IntegerValue) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IntegerValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.DoubleValue) {
        size += 1 + 8;
      }
      if (valueTypeCase_ == ValueTypeOneofCase.TimestampValue) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimestampValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.StringValue) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(StringValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.BytesValue) {
        size += 2 + pb::CodedOutputStream.ComputeBytesSize(BytesValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.ReferenceValue) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ReferenceValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.GeoPointValue) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GeoPointValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.ArrayValue) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ArrayValue);
      }
      if (valueTypeCase_ == ValueTypeOneofCase.MapValue) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MapValue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Value other) {
      if (other == null) {
        return;
      }
      switch (other.ValueTypeCase) {
        case ValueTypeOneofCase.NullValue:
          NullValue = other.NullValue;
          break;
        case ValueTypeOneofCase.BooleanValue:
          BooleanValue = other.BooleanValue;
          break;
        case ValueTypeOneofCase.IntegerValue:
          IntegerValue = other.IntegerValue;
          break;
        case ValueTypeOneofCase.DoubleValue:
          DoubleValue = other.DoubleValue;
          break;
        case ValueTypeOneofCase.TimestampValue:
          if (TimestampValue == null) {
            TimestampValue = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          TimestampValue.MergeFrom(other.TimestampValue);
          break;
        case ValueTypeOneofCase.StringValue:
          StringValue = other.StringValue;
          break;
        case ValueTypeOneofCase.BytesValue:
          BytesValue = other.BytesValue;
          break;
        case ValueTypeOneofCase.ReferenceValue:
          ReferenceValue = other.ReferenceValue;
          break;
        case ValueTypeOneofCase.GeoPointValue:
          if (GeoPointValue == null) {
            GeoPointValue = new global::Google.Type.LatLng();
          }
          GeoPointValue.MergeFrom(other.GeoPointValue);
          break;
        case ValueTypeOneofCase.ArrayValue:
          if (ArrayValue == null) {
            ArrayValue = new global::Google.Events.Protobuf.Cloud.Firestore.V1.ArrayValue();
          }
          ArrayValue.MergeFrom(other.ArrayValue);
          break;
        case ValueTypeOneofCase.MapValue:
          if (MapValue == null) {
            MapValue = new global::Google.Events.Protobuf.Cloud.Firestore.V1.MapValue();
          }
          MapValue.MergeFrom(other.MapValue);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BooleanValue = input.ReadBool();
            break;
          }
          case 16: {
            IntegerValue = input.ReadInt64();
            break;
          }
          case 25: {
            DoubleValue = input.ReadDouble();
            break;
          }
          case 42: {
            ReferenceValue = input.ReadString();
            break;
          }
          case 50: {
            global::Google.Events.Protobuf.Cloud.Firestore.V1.MapValue subBuilder = new global::Google.Events.Protobuf.Cloud.Firestore.V1.MapValue();
            if (valueTypeCase_ == ValueTypeOneofCase.MapValue) {
              subBuilder.MergeFrom(MapValue);
            }
            input.ReadMessage(subBuilder);
            MapValue = subBuilder;
            break;
          }
          case 66: {
            global::Google.Type.LatLng subBuilder = new global::Google.Type.LatLng();
            if (valueTypeCase_ == ValueTypeOneofCase.GeoPointValue) {
              subBuilder.MergeFrom(GeoPointValue);
            }
            input.ReadMessage(subBuilder);
            GeoPointValue = subBuilder;
            break;
          }
          case 74: {
            global::Google.Events.Protobuf.Cloud.Firestore.V1.ArrayValue subBuilder = new global::Google.Events.Protobuf.Cloud.Firestore.V1.ArrayValue();
            if (valueTypeCase_ == ValueTypeOneofCase.ArrayValue) {
              subBuilder.MergeFrom(ArrayValue);
            }
            input.ReadMessage(subBuilder);
            ArrayValue = subBuilder;
            break;
          }
          case 82: {
            global::Google.Protobuf.WellKnownTypes.Timestamp subBuilder = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            if (valueTypeCase_ == ValueTypeOneofCase.TimestampValue) {
              subBuilder.MergeFrom(TimestampValue);
            }
            input.ReadMessage(subBuilder);
            TimestampValue = subBuilder;
            break;
          }
          case 88: {
            valueType_ = input.ReadEnum();
            valueTypeCase_ = ValueTypeOneofCase.NullValue;
            break;
          }
          case 138: {
            StringValue = input.ReadString();
            break;
          }
          case 146: {
            BytesValue = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// An array value.
  /// </summary>
  public sealed partial class ArrayValue : pb::IMessage<ArrayValue> {
    private static readonly pb::MessageParser<ArrayValue> _parser = new pb::MessageParser<ArrayValue>(() => new ArrayValue());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ArrayValue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Firestore.V1.EventsReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ArrayValue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ArrayValue(ArrayValue other) : this() {
      values_ = other.values_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ArrayValue Clone() {
      return new ArrayValue(this);
    }

    /// <summary>Field number for the "values" field.</summary>
    public const int ValuesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Google.Events.Protobuf.Cloud.Firestore.V1.Value> _repeated_values_codec
        = pb::FieldCodec.ForMessage(10, global::Google.Events.Protobuf.Cloud.Firestore.V1.Value.Parser);
    private readonly pbc::RepeatedField<global::Google.Events.Protobuf.Cloud.Firestore.V1.Value> values_ = new pbc::RepeatedField<global::Google.Events.Protobuf.Cloud.Firestore.V1.Value>();
    /// <summary>
    /// Values in the array.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Google.Events.Protobuf.Cloud.Firestore.V1.Value> Values {
      get { return values_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ArrayValue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ArrayValue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!values_.Equals(other.values_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= values_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      values_.WriteTo(output, _repeated_values_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += values_.CalculateSize(_repeated_values_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ArrayValue other) {
      if (other == null) {
        return;
      }
      values_.Add(other.values_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            values_.AddEntriesFrom(input, _repeated_values_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// A map value.
  /// </summary>
  public sealed partial class MapValue : pb::IMessage<MapValue> {
    private static readonly pb::MessageParser<MapValue> _parser = new pb::MessageParser<MapValue>(() => new MapValue());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MapValue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Firestore.V1.EventsReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MapValue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MapValue(MapValue other) : this() {
      fields_ = other.fields_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MapValue Clone() {
      return new MapValue(this);
    }

    /// <summary>Field number for the "fields" field.</summary>
    public const int FieldsFieldNumber = 1;
    private static readonly pbc::MapField<string, global::Google.Events.Protobuf.Cloud.Firestore.V1.Value>.Codec _map_fields_codec
        = new pbc::MapField<string, global::Google.Events.Protobuf.Cloud.Firestore.V1.Value>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Google.Events.Protobuf.Cloud.Firestore.V1.Value.Parser), 10);
    private readonly pbc::MapField<string, global::Google.Events.Protobuf.Cloud.Firestore.V1.Value> fields_ = new pbc::MapField<string, global::Google.Events.Protobuf.Cloud.Firestore.V1.Value>();
    /// <summary>
    /// The map's fields.
    ///
    /// The map keys represent field names. Field names matching the regular
    /// expression `__.*__` are reserved. Reserved field names are forbidden except
    /// in certain documented contexts. The map keys, represented as UTF-8, must
    /// not exceed 1,500 bytes and cannot be empty.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::Google.Events.Protobuf.Cloud.Firestore.V1.Value> Fields {
      get { return fields_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MapValue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MapValue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Fields.Equals(other.Fields)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Fields.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      fields_.WriteTo(output, _map_fields_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += fields_.CalculateSize(_map_fields_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MapValue other) {
      if (other == null) {
        return;
      }
      fields_.Add(other.fields_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            fields_.AddEntriesFrom(input, _map_fields_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
