// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/events/cloudevent.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Events.Protobuf {

  /// <summary>Holder for reflection information generated from google/events/cloudevent.proto</summary>
  public static partial class CloudeventReflection {

    #region Descriptor
    /// <summary>File descriptor for google/events/cloudevent.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CloudeventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5nb29nbGUvZXZlbnRzL2Nsb3VkZXZlbnQucHJvdG8SDWdvb2dsZS5ldmVu",
            "dHMaIGdvb2dsZS9wcm90b2J1Zi9kZXNjcmlwdG9yLnByb3RvOjsKEGNsb3Vk",
            "X2V2ZW50X3R5cGUSHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMY",
            "oJwBIAEoCUIZqgIWR29vZ2xlLkV2ZW50cy5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { CloudeventExtensions.CloudEventType }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of google/events/cloudevent.proto</summary>
  public static partial class CloudeventExtensions {
    /// <summary>
    /// FIXME: Determine the right field number to use
    /// TODO: Use a message instead of just a string?
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string> CloudEventType =
      new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string>(20000, pb::FieldCodec.ForString(160002, ""));
  }

}

#endregion Designer generated code
