# Validates Functions Framework with GCF buildpacks.
name: Buildpack Integration Test
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
  # Runs every day on 12:00 AM PST
  schedule:
    - cron: "0 0 * * *"

# Declare default permissions as read only.
permissions: read-all

jobs:
  dotnet6:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@main
    with:
      # This builds a local copy of the Functions Framework, and creates
      # a standalone copy of the conformance test function in tmp
      # with a NuGet config file to use the local FF.
      prerun: 'src/Google.Cloud.Functions.ConformanceTests/create-standalone.sh'
      http-builder-source: 'tmp/Google.Cloud.Functions.ConformanceTests'
      http-builder-target: 'HttpFunction'
      cloudevent-builder-source: 'tmp/Google.Cloud.Functions.ConformanceTests'
      cloudevent-builder-target: 'UntypedCloudEventFunction'
      builder-runtime: 'dotnet'
      builder-runtime-version: '6'
      # Ask the test runner to wait for 5 seconds for the server to start
      # before sending it requests. It should come up much quicker
      # than that, but 5 seconds will rule out "slow startup" as
      # a failure mode.
      start-delay: 5
      # The conformance function writes to the current directory, which will be
      # /workspace/bin when run from the buildpack.
      output-file: bin/function_output.json
