name: .NET CI

on: [push, pull_request]

env:
  ContinuousIntegrationBuild: true
  Configuration: Release
  # When building examples, build against the version in this
  # repo rather than against NuGet; this allows us to make breaking
  # changes.
  LocalFunctionsFramework: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: setup
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
      run: dotnet build -nologo -clp:NoSummary -v quiet src
      run: dotnet build -nologo -clp:NoSummary -v quiet examples

    - name: Testing...
      run: dotnet test -nologo --no-build -v quiet src
      run: dotnet test -nologo --no-build -v quiet examples

    - name: Packing...
      run: rm -rf nupkg
      run: dotnet pack -nologo -v quiet src -o $PWD/nupkg

    - name: Created packages...
      run: ls nupkg